import assert from "node:assert/strict";
import test from "node:test";
import { Firestore } from "firebase-admin/firestore";
import { getBirdDetails, getCustomerDetails, getPairDetails, listBirds, listDeliveries, listEligibleCompletedSales, listHandovers, listPairs, listPayments, listReservations } from "../src/services/reads.js";

const db = new Firestore({ projectId: "birdsmyboss-v1-dev" });
const prefix = `reads-${Date.now()}-${Math.random().toString(36).slice(2)}`;
test("read DTOs are bounded, filtered, and omit internal fields", async () => {
  const birdId = `${prefix}-bird`, femaleId = `${prefix}-female`, hatchedBirdId = `${prefix}-hatched`, pairId = `${prefix}-pair`, cageId = `${prefix}-cage`, customerId = `${prefix}-customer`, reservationId = `${prefix}-reservation`, saleId = `${prefix}-sale`;
  await db.collection("birds").doc(birdId).set({ ringId: "READ-001", displayName: "Read bird", origin: "external", status: "active", publicToken: "operator-trusted-token", internalNotes: "do not leak" });
  await db.collection("birds").doc(hatchedBirdId).set({ ringId: "SMOKE-CHICK-01", displayName: "SMOKE CHICK 01", mutation: "Normal", origin: "farm_hatched", status: "active", eggId: `${prefix}-egg`, createdAt: new Date(), updatedAt: new Date() });
  await db.collection("sexHistory").doc(`${prefix}-sex-old`).set({ birdId, sex: "female", determinedOn: "2025-01-01", method: "dna" });
  await db.collection("sexHistory").doc(`${prefix}-sex-current`).set({ birdId, sex: "male", determinedOn: "2026-01-01", method: "visual" });
  await db.collection("weightHistory").doc(`${prefix}-weight`).set({ birdId, weightGrams: 85.5, measuredOn: "2026-08-14", createdAt: new Date(), internalNote: "do not leak" });
  await db.collection("birds").doc(femaleId).set({ ringId: "READ-F-001", displayName: "Read female", origin: "external", status: "active" });
  await db.collection("sexHistory").doc(`${prefix}-female-sex`).set({ birdId: femaleId, sex: "female", determinedOn: "2026-01-01", method: "dna" });
  await db.collection("pairs").doc(pairId).set({ status: "active", startedOn: "2026-01-01" });
  await db.collection("pairMembers").doc(`${prefix}-member-m`).set({ pairId, birdId, role: "male", effectiveFrom: "2026-01-01" });
  await db.collection("pairMembers").doc(`${prefix}-member-f`).set({ pairId, birdId: femaleId, role: "female", effectiveFrom: "2026-01-01" });
  await db.collection("cages").doc(cageId).set({ code: "READ-CAGE-01", name: "Read Cage", status: "active" });
  await db.collection("cageAssignments").doc(`${prefix}-assignment`).set({ pairId, cageId, startsOn: "2026-01-02" });
  await db.collection("breedingCycles").doc(`${prefix}-cycle`).set({ pairId, startedOn: "2026-01-03", status: "active" });
  await db.collection("eggs").doc(`${prefix}-egg`).set({ cycleId: `${prefix}-cycle`, sequenceNo: 1, laidOn: "2026-01-04", status: "laid" });
  await db.collection("customers").doc(customerId).set({ displayName: "Customer", phone: "1", address: "private" });
  await db.collection("reservations").doc(reservationId).set({ birdId, customerId, reservedOn: "2026-01-01", status: "active" });
  await db.collection("sales").doc(saleId).set({ birdId, customerId, status: "completed", createdOn: "2026-01-01", completedOn: "2026-01-02" });
  await db.collection("payments").doc(`${prefix}-payment`).set({ saleId, amount: 10, currency: "THB", receivedOn: "2026-01-01", paymentMethod: "cash", status: "received", secret: "no" });
  await db.collection("deliveries").doc(`${prefix}-delivery`).set({ saleId, distanceKm: 10, freeDistanceKm: 2, pricePerKm: 5, shippingFee: 40, currency: "THB", createdOn: "2026-01-02", status: "planned", secret: "no" });
  await db.collection("handovers").doc(`${prefix}-handover`).set({ saleId, birdId, sourceType: "sale", recipientSnapshot: { name: "Receiver", phone: "1" }, handoverOn: "2026-01-03", status: "completed", secret: "no" });
  const boundedBirds = await listBirds(db, { limit: 1 }); assert.equal(boundedBirds.length, 1);
  const birds = await listBirds(db, { limit: 50 }); const listedBird = birds.find(x => (x as Record<string, unknown>).birdId === birdId) as Record<string, unknown>; assert.equal("internalNotes" in listedBird, false); assert.equal(listedBird.currentSex, "male");
  const listedHatchedBird = birds.find(x => (x as Record<string, unknown>).birdId === hatchedBirdId) as Record<string, unknown>; assert.equal(listedHatchedBird.ringId, "SMOKE-CHICK-01"); assert.equal(listedHatchedBird.displayName, "SMOKE CHICK 01"); assert.equal(listedHatchedBird.mutation, "Normal"); assert.equal(listedHatchedBird.origin, "farm_hatched"); assert.equal(listedHatchedBird.status, "active"); assert.equal(listedHatchedBird.passportStatus, "draft"); assert.ok(birds.some(x => (x as Record<string, unknown>).origin === "external"));
  const details = await getBirdDetails(db, { birdId }); assert.equal(details.ringId, "READ-001"); assert.equal(details.publicToken, "operator-trusted-token"); assert.equal("internalNotes" in details, false); assert.deepEqual(details.weightHistory, [{ weightGrams: 85.5, measuredOn: "2026-08-14" }]);
  const pairs = await listPairs(db, { limit: 50 }); const listedPair = pairs.find(x => x.pairId === pairId)!; assert.equal((listedPair.members as Array<Record<string, unknown>>).find(x => x.role === "male")?.ringId, "READ-001");
  const pair = await getPairDetails(db, { pairId }); assert.equal(pair.startedOn, "2026-01-01"); assert.equal(pair.members.find(x => x.role === "female")?.displayName, "Read female"); assert.equal(pair.assignments[0].code, "READ-CAGE-01"); assert.equal(pair.cycles[0].startedOn, "2026-01-03"); assert.equal(pair.cycles[0].eggs[0].sequenceNo, 1);
  const reservations = await listReservations(db, { limit: 50 }); assert.ok(reservations.some(x => x.reservationId === reservationId));
  const payments = await listPayments(db, { limit: 50 }); assert.equal("secret" in payments.find(x => x.paymentId === `${prefix}-payment`)!, false);
  const deliveries = await listDeliveries(db, { limit: 50 }); const delivery = deliveries.find(x => x.deliveryId === `${prefix}-delivery`)!; assert.equal(delivery.currency, "THB"); assert.equal("secret" in delivery, false);
  const handovers = await listHandovers(db, { limit: 50 }); const handover = handovers.find(x => x.handoverId === `${prefix}-handover`)!; assert.deepEqual(handover.recipientSnapshot, { name: "Receiver", phone: "1" }); assert.equal("secret" in handover, false);
  assert.ok((await listEligibleCompletedSales(db, { limit: 10 })).some(x => x.saleId === saleId));
  const customer = await getCustomerDetails(db, { customerId }); assert.equal(customer.phone, "1"); assert.ok(customer.sales.some(x => x.saleId === saleId));
});
