import { FormEvent, useEffect, useState } from "react";
import { DateInput } from "./DateInput";
import { isoToThaiDisplay, parseThaiDisplayDate, thaiDisplayToIso } from "./date";
import { invoke, thaiError } from "./functions";
import { PassportAdmin as PassportAdminPanel } from "./components/PassportAdmin";
import { PassportWorkflow } from "./PassportWorkflow";
import { Commercial } from "./Commercial";
import { Customers } from "./Customers";
import { DeliveryHandover } from "./DeliveryHandover";
import { Giveaways } from "./Giveaways";
import { displayValue } from "./presentation";
import { EmptyState, PageHeader, SectionCard, StatusBadge } from "./ui";
import { BirdProfile } from "./BirdProfile";
import { BirdAssets } from "./BirdAssets";
import { PriceHistory } from "./PriceHistory";
import { Dashboard } from "./Dashboard";
import { OrangeRing, PairRelationship } from "./bmb-design-system";
import "./BirdsRegistry.css";
import "./Breeding.css";

type Row = Record<string, any>;
type Page = "Dashboard" | "Birds" | "Breeding" | "Sales" | "Giveaways" | "Customers" | "Delivery & Handover" | "Passport";
const pages: Page[] = ["Dashboard", "Birds", "Breeding", "Sales", "Giveaways", "Customers", "Delivery & Handover", "Passport"];
const label = displayValue;

type FormField = [string, string, "text" | "number" | "date" | "select", boolean, options?: readonly string[]];
function Form({ title, operation, fields, refresh, initialValues = {}, resetOnSuccess = false }: { title: string; operation: string; fields: FormField[]; refresh: () => void; initialValues?: Row; resetOnSuccess?: boolean }) {
  const [values, setValues] = useState<Row>(() => ({ ...initialValues })); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const isCheck=operation==="checkRingIdAvailability";
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const body = Object.fromEntries(Object.entries(values).filter(([, v]) => v !== "" && v !== undefined)); if (typeof body.recipientSnapshot === "string") body.recipientSnapshot = JSON.parse(body.recipientSnapshot); await invoke(operation, body); setMessage(isCheck?"ตรวจสอบสำเร็จ":"บันทึกสำเร็จ"); if (resetOnSuccess) setValues({ ...initialValues }); refresh(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <form className="card" onSubmit={submit}><h3>{title}</h3>{fields.map(([key, text, type, required, options]) => <label className="field" key={key}>{text}{required && " *"}{type === "date" ? <DateInput label={text} required={required} value={values[key]} onChange={(v) => setValues({ ...values, [key]: v })} /> : type === "select" ? <select required={required} value={String(values[key] ?? "")} onChange={(e) => setValues({ ...values, [key]: e.target.value })}><option value="" disabled>เลือก</option>{options?.map(option => <option key={option} value={option}>{displayValue(option)}</option>)}</select> : <input type={type} required={required} value={String(values[key] ?? "")} onChange={(e) => setValues({ ...values, [key]: type === "number" ? Number(e.target.value) : e.target.value })} />}</label>)}<button disabled={busy}>{busy?(isCheck?"กำลังตรวจสอบ…":"กำลังบันทึก…"):(isCheck?"ตรวจสอบ":"บันทึก")}</button>{message && <p className="muted">{message}</p>}</form>;
}

const parentResultLimit = 8;
function ParentSelector({ role, birds, selected, otherId, onSelect }: { role: "male" | "female"; birds: Row[]; selected: Row | null; otherId?: string; onSelect: (bird: Row | null) => void }) {
  const [query, setQuery] = useState("");
  const title = role === "male" ? "พ่อนก" : "แม่นก";
  const eligible = birds.filter(bird => bird.currentSex === role && bird.birdId !== otherId);
  const normalized = query.trim().toLocaleLowerCase();
  const matches = eligible.filter(bird => !normalized || String(bird.ringId ?? "").toLocaleLowerCase().includes(normalized) || String(bird.displayName ?? "").toLocaleLowerCase().includes(normalized)).slice(0, parentResultLimit);
  if (selected) return <section className="card" aria-label={`เลือก${title}แล้ว`}><strong>{title}</strong><p>{label(selected.displayName)}</p><p>Ring ID: {label(selected.ringId)}</p>{(selected.mutation||selected.origin)&&<p>{selected.mutation?`Mutation: ${label(selected.mutation)}`:""}{selected.mutation&&selected.origin?" · ":""}{selected.origin?`Origin: ${label(selected.origin)}`:""}</p>}<button type="button" onClick={() => onSelect(null)}>เปลี่ยน</button></section>;
  return <section className="card"><label className="field">{title} *<input aria-label={`ค้นหา${title}`} placeholder="ค้นหาจาก Ring ID หรือชื่อนก..." value={query} onChange={event => setQuery(event.target.value)} /></label>{eligible.length === 0 ? <p className="muted">{role === "male" ? "ไม่มีนกเพศผู้ที่มีสิทธิ์เลือก" : "ไม่มีนกเพศเมียที่มีสิทธิ์เลือก"}</p> : matches.length === 0 ? <p className="muted">ไม่พบนกที่ตรงกับการค้นหา</p> : <div className="list" role="listbox" aria-label={`ผลการค้นหา${title}`}>{matches.map(bird => <button type="button" className="row" role="option" aria-selected="false" key={bird.birdId} onClick={() => { onSelect(bird); setQuery(""); }}><span><b>{label(bird.displayName)}</b></span><span>Ring ID: {label(bird.ringId)}</span><span>{bird.mutation?label(bird.mutation):""}{bird.mutation&&bird.origin?" · ":""}{bird.origin?label(bird.origin):""}{(bird.mutation||bird.origin)&&bird.status?" · ":""}{bird.status?label(bird.status):""}</span></button>)}</div>}</section>;
}

function PairForm({ birds, refresh }: { birds: Row[]; refresh: () => void }) {
  const [father, setFather] = useState<Row | null>(null); const [mother, setMother] = useState<Row | null>(null); const [dateText, setDateText] = useState(""); const [dateError, setDateError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const changeDate = (raw: string) => { const digits = raw.replace(/\D/g, "").slice(0, 8); if (digits.length !== 8) { setDateText(digits); setDateError(""); return; } const formatted = parseThaiDisplayDate(digits); setDateText(formatted ?? digits); setDateError(formatted ? "" : "กรุณากรอกวันที่ที่มีอยู่จริง"); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const startedOn = thaiDisplayToIso(dateText); if (!father || !mother) { setMessage("กรุณาเลือกพ่อนกและแม่นก"); return; } if (father.birdId === mother.birdId) { setMessage("พ่อนกและแม่นกต้องเป็นคนละตัว"); return; } if (!startedOn) { setDateError("กรุณากรอกวันที่ที่มีอยู่จริง"); return; } setBusy(true); try { await invoke("createPair", { maleBirdId: father.birdId, femaleBirdId: mother.birdId, startedOn }); setMessage("บันทึกสำเร็จ"); setFather(null); setMother(null); setDateText(""); refresh(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <form className="card" onSubmit={submit}><h3>สร้างคู่</h3><ParentSelector role="male" birds={birds} selected={father} otherId={mother?.birdId} onSelect={setFather}/><ParentSelector role="female" birds={birds} selected={mother} otherId={father?.birdId} onSelect={setMother}/><label className="field">วันเริ่ม *<input required aria-label="วันเริ่ม" placeholder="DD/MM/YYYY" inputMode="numeric" value={dateText} aria-invalid={Boolean(dateError)} onChange={event => changeDate(event.target.value)} /></label>{dateError && <small className="field-error" role="alert">{dateError}</small>}<button disabled={busy}>{busy ? "กำลังบันทึก…" : "บันทึก"}</button>{message && <p role="status">{message}</p>}</form>;
}

function DetailList({ title, rows, idKey, operation, cages = [], onDetailChange }: { title: string; rows: Row[]; idKey: string; operation?: string; cages?: Row[]; onDetailChange?: (open: boolean) => void }) {
  const [detail, setDetail] = useState<Row | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [query,setQuery]=useState("");
  const normalized=query.trim().toLocaleLowerCase(); const visibleRows=idKey==="birdId"?rows.filter(row=>!normalized||[row.ringId,row.displayName,row.mutation,row.currentSex].some(value=>String(value??"").toLocaleLowerCase().includes(normalized))):rows;
  const open = async (row: Row) => { if (!operation) return; setLoading(true); setError(""); try { setDetail(await invoke(operation, { [idKey]: row[idKey] }) as Row); onDetailChange?.(true); } catch (caught) { setError(thaiError(caught)); } finally { setLoading(false); } };
  const refreshDetail = async () => { if (!detail || !operation) return; setDetail(await invoke(operation, { [idKey]: detail[idKey] }) as Row); };
  if (detail) return <section className="section-card"><h3>{operation === "getPairDetails" ? "คู่" : title} — รายละเอียด</h3>{operation === "getPairDetails"&&<p>สถานะ: {label(detail.status)}</p>}<button type="button" onClick={() => { setDetail(null); onDetailChange?.(false); }}>← กลับไป{title}</button>{operation === "getBirdDetails" && <BirdDetail data={detail} onChanged={refreshDetail} />}{operation === "getPairDetails" && <PairDetail data={detail} cages={cages} onChanged={refreshDetail} />}</section>;
  if(idKey==="birdId")return <section className="flock-registry" aria-labelledby="flock-registry-title"><header className="flock-registry-heading"><div><small>THE FLOCK REGISTRY</small><h2 id="flock-registry-title">นกในความดูแล</h2><p>ตัวตนของนกทุกตัวในฟาร์ม เรียงพร้อมสำหรับการค้นหาและทำงาน</p></div><div className="flock-count"><span>FLOCK INDEX</span><strong>{visibleRows.length}</strong><small>Bird identities</small></div></header><label className="flock-search"><span>ค้นหานกของฉัน</span><input aria-label="ค้นหาทะเบียนนก" placeholder="Ring ID, ชื่อ, Mutation หรือเพศ" value={query} onChange={event=>setQuery(event.target.value)}/><small>ค้นหาจากข้อมูลที่รองรับอยู่แล้วในทะเบียน</small></label>{loading&&<p className="muted">กำลังโหลดข้อมูล…</p>}{error&&<p role="alert">{error}</p>}{visibleRows.length?<div className="flock-list">{visibleRows.map((row,i)=><button type="button" className="bird-registry-row" key={String(row.birdId??i)} aria-label={`Ring ID: ${label(row.ringId)} · Display Name: ${label(row.displayName)} · Mutation: ${label(row.mutation)} · Origin: ${label(row.origin)} · Sex: ${label(row.currentSex)} · Status: ${label(row.status)}`} onClick={()=>open(row)}><span className="bird-registry-identity"><small>{String(i+1).padStart(2,"0")}</small><OrangeRing variant="compact"/><span><b>{label(row.displayName)}</b><em><small>Ring ID</small><strong>{label(row.ringId)}</strong></em></span></span><span className="bird-registry-meta"><small>Mutation</small><b>{label(row.mutation)}</b></span><span className="bird-registry-meta"><small>Origin</small><b>{label(row.origin)}</b></span><span className="bird-registry-meta"><small>Sex</small><b>{label(row.currentSex)}</b></span><span className="bird-registry-status"><StatusBadge status={row.status}/></span><span className="bird-registry-open">ดู <b>→</b></span></button>)}</div>:<EmptyState title={normalized?"ไม่พบนกที่ตรงกับการค้นหา":"ยังไม่มีข้อมูล"} description={normalized?"ลองค้นหาด้วย Ring ID หรือชื่ออื่น":"ข้อมูลใหม่จะแสดงที่นี่หลังบันทึกสำเร็จ"}/>}</section>;
  return <SectionCard title={title}>{loading && <p className="muted">กำลังโหลดข้อมูล…</p>}{error && <p role="alert">{error}</p>}{visibleRows.length ? <div className={idKey==="pairId"?"pair-registry":"list"}>{visibleRows.map((row, i) => <button type="button" className={idKey==="pairId"?"pair-registry-row":"row"} aria-label={idKey==="pairId"?`พ่อนก: ${label(pairMember(row,"male")?.displayName)} · Ring ID: ${label(pairMember(row,"male")?.ringId)} · แม่นก: ${label(pairMember(row,"female")?.displayName)} · Ring ID: ${label(pairMember(row,"female")?.ringId)} · Status: ${label(row.status)} · ${isoToThaiDisplay(row.startedOn)||"-"}`:undefined} key={String(row[idKey] ?? i)} onClick={() => open(row)}>{idKey === "pairId" ? <PairRegistryIdentity pair={row}/> : idKey === "cageId" ? <><span className="entity-primary"><b>{label(row.name)}</b><small>Code: {label(row.code)}</small></span><span><b>Status: </b>{label(row.status)}</span><StatusBadge status={row.status}/></> : <><span className="entity-primary"><b>Display Name: {label(row.displayName)}</b><small>{label(row.phone)}</small></span><span>{label(row.email)}</span><span><b>Status: </b>{label(row.status)}</span><StatusBadge status={row.status}/></>}</button>)}</div> : <EmptyState title="ยังไม่มีข้อมูล" description="ข้อมูลใหม่จะแสดงที่นี่หลังบันทึกสำเร็จ"/>}</SectionCard>;
}
const methodOptions = [{ value: "dna", label: "DNA" }, { value: "sex_linked", label: "Sex Linked" }, { value: "visual", label: "Visual" }, { value: "unknown", label: "Unknown" }] as const;
function SexHistoryForm({ bird, onSaved }: { bird: Row; onSaved: () => Promise<void> }) {
  const [sex, setSex] = useState(""); const [method, setMethod] = useState(""); const [dateText, setDateText] = useState(""); const [dateError, setDateError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const changeDate = (raw: string) => { const digits = raw.replace(/\D/g, "").slice(0, 8); if (digits.length !== 8) { setDateText(digits); setDateError(""); return; } const formatted = parseThaiDisplayDate(digits); setDateText(formatted ?? digits); setDateError(formatted ? "" : "กรุณากรอกวันที่ที่มีอยู่จริง"); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const determinedOn = thaiDisplayToIso(dateText); if (!determinedOn) { setDateError("กรุณากรอกวันที่ที่มีอยู่จริง"); return; } setBusy(true); try { await invoke("recordSexHistory", { birdId: bird.birdId, sex, method, determinedOn }); setMessage("บันทึกสำเร็จ"); setSex(""); setMethod(""); setDateText(""); await onSaved(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <form className="card" onSubmit={submit}><h4>บันทึกเพศ</h4><p>นก: {label(bird.displayName)}</p><p>Ring ID: {label(bird.ringId)}</p><label className="field">เพศ *<select required value={sex} onChange={e => setSex(e.target.value)}><option value="" disabled>เลือก</option>{["male","female","unknown"].map(value => <option key={value} value={value}>{displayValue(value)}</option>)}</select></label><label className="field">วิธี *<select required value={method} onChange={e => setMethod(e.target.value)}><option value="" disabled>เลือก</option>{methodOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="field">วันที่ *<input required value={dateText} placeholder="DD/MM/YYYY" inputMode="numeric" aria-label="วันที่" aria-invalid={Boolean(dateError)} onChange={e => changeDate(e.target.value)} /></label>{dateError && <small className="field-error" role="alert">{dateError}</small>}<button disabled={busy}>{busy ? "กำลังบันทึก…" : "บันทึก"}</button>{message && <p role="status">{message}</p>}</form>;
}

function WeightHistoryForm({ bird, onSaved }: { bird: Row; onSaved: () => Promise<void> }) {
  const [weightText,setWeightText]=useState(""); const [dateText,setDateText]=useState(""); const [weightError,setWeightError]=useState(""); const [dateError,setDateError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const changeDate=(raw:string)=>{const digits=raw.replace(/\D/g,"").slice(0,8);if(digits.length!==8){setDateText(digits);setDateError("");return;}const formatted=parseThaiDisplayDate(digits);setDateText(formatted??digits);setDateError(formatted?"":"กรุณากรอกวันที่ที่มีอยู่จริง");};
  const submit=async(event:FormEvent)=>{event.preventDefault();const weightGrams=Number(weightText),measuredOn=thaiDisplayToIso(dateText);const validWeight=weightText.trim()!==""&&Number.isFinite(weightGrams)&&weightGrams>0;if(!validWeight)setWeightError("น้ำหนักต้องเป็นตัวเลขมากกว่าศูนย์");else setWeightError("");if(!measuredOn)setDateError("กรุณากรอกวันที่ที่มีอยู่จริง");if(!validWeight||!measuredOn)return;setBusy(true);try{await invoke("recordWeightHistory",{birdId:bird.birdId,weightGrams,measuredOn});setMessage("บันทึกสำเร็จ");setWeightText("");setDateText("");await onSaved();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};
  return <form className="card" onSubmit={submit}><h4>บันทึกน้ำหนัก</h4><p>นก: {label(bird.displayName)}</p><p>Ring ID: {label(bird.ringId)}</p><label className="field">น้ำหนัก (กรัม) *<input required type="number" step="any" aria-label="น้ำหนัก (กรัม)" value={weightText} aria-invalid={Boolean(weightError)} onChange={event=>setWeightText(event.target.value)}/></label>{weightError&&<small className="field-error" role="alert">{weightError}</small>}<label className="field">วันที่ *<input required aria-label="วันที่บันทึกน้ำหนัก" placeholder="DD/MM/YYYY" inputMode="numeric" value={dateText} aria-invalid={Boolean(dateError)} onChange={event=>changeDate(event.target.value)}/></label>{dateError&&<small className="field-error" role="alert">{dateError}</small>}<button disabled={busy}>{busy?"กำลังบันทึก…":"บันทึก"}</button>{message&&<p role="status">{message}</p>}</form>;
}

function BirdDetail({ data, onChanged }: { data: Row; onChanged: () => Promise<void> }) { const histories = Array.isArray(data.sexHistory) ? data.sexHistory as Row[] : []; const weights=Array.isArray(data.weightHistory)?data.weightHistory as Row[]:[]; const currentSex=[...histories].sort((a,b)=>String(b.determinedOn??"").localeCompare(String(a.determinedOn??"")))[0]?.sex??data.currentSex??"unknown"; return <BirdProfile data={data} currentSex={currentSex} sexHistory={histories} weightHistory={weights} forms={<><div className="form-grid"><SexHistoryForm bird={data} onSaved={onChanged}/><WeightHistoryForm bird={data} onSaved={onChanged}/></div><BirdAssets birdId={String(data.birdId)} photos={data.photos??[]} documents={data.documents??[]} onSaved={onChanged}/></>} passport={<PassportAdminPanel birdId={String(data.birdId)} passportStatus={data.passportStatus} publicToken={data.publicToken} photos={data.photos} documents={data.documents} onChanged={onChanged}/>} priceHistory={<PriceHistory birdId={String(data.birdId)} onSaved={onChanged}/>}/>; }
const pairMember = (data: Row, role: "male" | "female") => Array.isArray(data.members) ? data.members.find((member: Row) => member.role === role) as Row | undefined : undefined;
function PairRegistryIdentity({ pair }: { pair: Row }) { const father = pairMember(pair, "male"), mother = pairMember(pair, "female"); return <><PairRelationship compact leftName={label(father?.displayName)} leftIdentifier={label(father?.ringId)} rightName={label(mother?.displayName)} rightIdentifier={label(mother?.ringId)}/><span className="pair-registry-date"><small>เริ่มความสัมพันธ์</small><strong>{isoToThaiDisplay(pair.startedOn) || "-"}</strong></span><StatusBadge status={pair.status}/><span className="pair-registry-open">ดู <b>→</b></span></>; }

function PairActivation({ pairId, onChanged, onSuccess }: { pairId: string; onChanged: () => Promise<void>; onSuccess: (message: string) => void }) {
  const [dateText, setDateText] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); const activeOn = thaiDisplayToIso(dateText); if (!activeOn) { setMessage("กรุณากรอกวันที่ที่มีอยู่จริง"); return; } setBusy(true); try { await invoke("activatePair", { pairId, activeOn }); onSuccess("เปิดใช้งานคู่สำเร็จ"); await onChanged(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <form className="card" onSubmit={submit}><h4>เปิดใช้งานคู่</h4><label className="field">วันที่เปิดใช้งาน *<input required aria-label="วันที่เปิดใช้งาน" placeholder="DD/MM/YYYY" inputMode="numeric" value={dateText} onChange={event => { const digits=event.target.value.replace(/\D/g,"").slice(0,8); setDateText(digits.length===8 ? parseThaiDisplayDate(digits) ?? digits : digits); }} /></label><button disabled={busy}>{busy ? "กำลังบันทึก…" : "เปิดใช้งาน"}</button>{message && <p role="status">{message}</p>}</form>;
}

function CageAssignment({ pairId, cages, onChanged, onSuccess }: { pairId: string; cages: Row[]; onChanged: () => Promise<void>; onSuccess: (message: string) => void }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Row | null>(null); const [startsOnText, setStartsOnText] = useState(""); const [endsOnText, setEndsOnText] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const eligible = cages.filter(cage => cage.status === "active"); const normalized=query.trim().toLocaleLowerCase(); const matches=eligible.filter(cage => !normalized || String(cage.code??"").toLocaleLowerCase().includes(normalized) || String(cage.name??"").toLocaleLowerCase().includes(normalized)).slice(0,8);
  const dateChange = (raw: string, setter: (value: string) => void) => { const digits=raw.replace(/\D/g,"").slice(0,8); setter(digits.length===8 ? parseThaiDisplayDate(digits) ?? digits : digits); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const startsOn=thaiDisplayToIso(startsOnText), endsOn=endsOnText ? thaiDisplayToIso(endsOnText) : undefined; if(!selected){setMessage("กรุณาเลือกกรง");return;} if(!startsOn || (endsOnText && !endsOn)){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;} setBusy(true); try { await invoke("assignPairToCage",{pairId,cageId:selected.cageId,startsOn,...(endsOn?{endsOn}:{})}); onSuccess("จัดคู่เข้ากรงสำเร็จ"); await onChanged(); } catch(error){setMessage(thaiError(error));} finally{setBusy(false);} };
  return <form className="card" onSubmit={submit}><h4>จัดคู่เข้ากรง</h4>{selected ? <section className="card"><strong>{label(selected.name)}</strong><p>Code: {label(selected.code)}</p><p>Status: {label(selected.status)}</p><button type="button" onClick={()=>setSelected(null)}>เปลี่ยน</button></section> : <><label className="field">ค้นหากรง *<input aria-label="ค้นหากรง" placeholder="ค้นหาจาก Code หรือชื่อกรง..." value={query} onChange={event=>setQuery(event.target.value)}/></label>{eligible.length===0?<p className="muted">ไม่มีกรงที่พร้อมใช้งาน</p>:matches.length===0?<p className="muted">ไม่พบกรงที่ตรงกับการค้นหา</p>:<div className="list" role="listbox" aria-label="ผลการค้นหากรง">{matches.map(cage=><button type="button" role="option" aria-selected="false" className="row" key={cage.cageId} onClick={()=>{setSelected(cage);setQuery("");}}><span><b>{label(cage.name)}</b></span><span>Code: {label(cage.code)}</span><span>Status: {label(cage.status)}</span></button>)}</div>}</>}<label className="field">วันเริ่ม *<input required aria-label="วันเริ่มจัดกรง" placeholder="DD/MM/YYYY" inputMode="numeric" value={startsOnText} onChange={event=>dateChange(event.target.value,setStartsOnText)}/></label><label className="field">วันสิ้นสุด<input aria-label="วันสิ้นสุดจัดกรง" placeholder="DD/MM/YYYY" inputMode="numeric" value={endsOnText} onChange={event=>dateChange(event.target.value,setEndsOnText)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"จัดเข้ากรง"}</button>{message&&<p role="status">{message}</p>}</form>;
}

function PairLifecycle({ pairId, onChanged }: { pairId: string; onChanged: () => Promise<void> }) { const [target,setTarget]=useState<"inactive"|"retired">("inactive"),[date,setDate]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false); const submit=async(event:FormEvent)=>{event.preventDefault();const endedOn=thaiDisplayToIso(date);if(!endedOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{await invoke(target==="inactive"?"deactivatePair":"retirePair",{pairId,endedOn});setMessage("อัปเดตสถานะคู่สำเร็จ");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}}; return <form className="card" onSubmit={submit}><h4>สถานะคู่เพาะ</h4><label className="field">การดำเนินการ<select aria-label="การดำเนินการคู่" value={target} onChange={event=>setTarget(event.target.value as "inactive"|"retired")}><option value="inactive">พักคู่ชั่วคราว</option><option value="retired">ยุติคู่ถาวร</option></select></label><label className="field">วันที่สิ้นสุด *<input required aria-label="วันที่สิ้นสุดคู่" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event=>changeThaiDate(event.target.value,setDate)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"ยืนยัน"}</button>{message&&<p role="status">{message}</p>}</form>; }
function PairReactivation({ pairId,onChanged }: { pairId:string;onChanged:()=>Promise<void> }) { const [date,setDate]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();const activeOn=thaiDisplayToIso(date);if(!activeOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{await invoke("reactivatePair",{pairId,activeOn});setMessage("เปิดใช้งานคู่สำเร็จ");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};return <form className="card" onSubmit={submit}><h4>เปิดใช้งานคู่ใหม่</h4><label className="field">วันที่เปิดใช้งาน *<input required aria-label="วันที่เปิดใช้งานคู่ใหม่" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event=>changeThaiDate(event.target.value,setDate)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"เปิดใช้งาน"}</button>{message&&<p role="status">{message}</p>}</form>; }
function AssignmentEnd({ assignment,onChanged }: { assignment:Row;onChanged:()=>Promise<void> }) { const [date,setDate]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();const endsOn=thaiDisplayToIso(date);if(!endsOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{await invoke("closeCageAssignment",{cageAssignmentId:assignment.cageAssignmentId,endsOn});setMessage("ปิดการจัดกรงสำเร็จ");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};return <form className="card" onSubmit={submit}><h4>สิ้นสุดการจัดกรง</h4><label className="field">วันที่สิ้นสุด *<input required aria-label="วันที่สิ้นสุดจัดกรง" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event=>changeThaiDate(event.target.value,setDate)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"ยืนยัน"}</button>{message&&<p role="status">{message}</p>}</form>; }
function AssignmentMove({ pairId,cages,onChanged }: { pairId:string;cages:Row[];onChanged:()=>Promise<void> }) { const [cageId,setCageId]=useState(""),[date,setDate]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();const startsOn=thaiDisplayToIso(date);if(!cageId||!startsOn){setMessage("กรุณาเลือกกรงและวันที่ให้ครบ");return;}setBusy(true);try{await invoke("movePairToCage",{pairId,cageId,startsOn});setMessage("ย้ายกรงสำเร็จ");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};return <form className="card" onSubmit={submit}><h4>ย้ายกรง</h4><label className="field">กรง<select aria-label="กรงใหม่" value={cageId} onChange={event=>setCageId(event.target.value)}><option value="">เลือกกรง</option>{cages.filter(cage=>cage.status==="active").map(cage=><option key={cage.cageId} value={cage.cageId}>{label(cage.code)} / {label(cage.name)}</option>)}</select></label><label className="field">วันเริ่ม *<input required aria-label="วันเริ่มย้ายกรง" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event=>changeThaiDate(event.target.value,setDate)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"ย้ายกรง"}</button>{message&&<p role="status">{message}</p>}</form>; }
const changeThaiDate = (raw: string, setter: (value: string) => void) => { const digits=raw.replace(/\D/g,"").slice(0,8); setter(digits.length===8 ? parseThaiDisplayDate(digits) ?? digits : digits); };

function EggForm({ cycle, pair, onChanged }: { cycle: Row; pair: Row; onChanged: () => Promise<void> }) {
  const eggs=Array.isArray(cycle.eggs)?cycle.eggs as Row[]:[]; const nextSequence=Math.max(0,...eggs.map(egg=>Number(egg.sequenceNo)||0))+1;
  const [dateText,setDateText]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const father=pairMember(pair,"male"),mother=pairMember(pair,"female"),assignments=Array.isArray(pair.assignments)?pair.assignments as Row[]:[],cage=assignments.find(assignment=>!assignment.endsOn)??assignments.at(-1);
  const submit=async(event:FormEvent)=>{event.preventDefault();const laidOn=thaiDisplayToIso(dateText);if(!laidOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{await invoke("createEgg",{cycleId:cycle.breedingCycleId,sequenceNo:nextSequence,laidOn});setMessage("เพิ่มไข่สำเร็จ");setDateText("");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};
  return <form className="card" onSubmit={submit}><h5>เพิ่มไข่</h5><p>คู่: {label(father?.displayName)} · Ring ID: {label(father?.ringId)} / {label(mother?.displayName)} · Ring ID: {label(mother?.ringId)}</p><p>รอบเพาะ: {isoToThaiDisplay(cycle.startedOn)||"-"} · {label(cycle.status)}</p>{cage&&<p>กรง: {label(cage.code)} / {label(cage.name)}</p>}<p>ลำดับ: {nextSequence}</p><label className="field">วันที่ไข่ *<input required aria-label="วันที่ไข่" placeholder="DD/MM/YYYY" inputMode="numeric" value={dateText} onChange={event=>changeThaiDate(event.target.value,setDateText)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"เพิ่มไข่"}</button>{message&&<p role="status">{message}</p>}</form>;
}

function HatchEggForm({ egg, onChanged }: { egg: Row; onChanged: () => Promise<void> }) {
  const [ringId,setRingId]=useState(""); const [displayName,setDisplayName]=useState(""); const [mutation,setMutation]=useState(""); const [hatchedOnText,setHatchedOnText]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();const hatchedOn=hatchedOnText?thaiDisplayToIso(hatchedOnText):undefined;if(hatchedOnText&&!hatchedOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{await invoke("createBirdFromEgg",{eggId:egg.eggId,ringId,displayName,origin:"farm_hatched",...(mutation.trim()?{mutation:mutation.trim()}:{}),...(hatchedOn?{hatchedOn}:{})});setMessage("สร้างนกจากไข่สำเร็จ");setRingId("");setDisplayName("");setMutation("");setHatchedOnText("");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};
  return <form className="card" onSubmit={submit}><h6>บันทึกการฟักและสร้างนก</h6><p>ใช้ไข่ที่เลือกและ Origin: Farm Hatched โดยอัตโนมัติ</p><label className="field">Ring ID *<input required aria-label="Ring ID ของลูกนก" value={ringId} onChange={event=>setRingId(event.target.value)}/></label><label className="field">ชื่อลูกนก *<input required aria-label="ชื่อลูกนก" value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label><label className="field">Mutation/สี<input aria-label="Mutation ของลูกนก" value={mutation} onChange={event=>setMutation(event.target.value)}/></label><label className="field">วันฟัก<input aria-label="วันฟัก" placeholder="DD/MM/YYYY" inputMode="numeric" value={hatchedOnText} onChange={event=>changeThaiDate(event.target.value,setHatchedOnText)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"สร้างนกจากไข่"}</button>{message&&<p role="status">{message}</p>}</form>;
}

function EggStatusAction({egg,onChanged}:{egg:Row;onChanged:()=>Promise<void>}){const [targetStatus,setTargetStatus]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const options=egg.status==="laid"?["fertile","infertile","lost","discarded"]:egg.status==="fertile"?["lost","discarded"]:[];const submit=async(event:FormEvent)=>{event.preventDefault();if(!targetStatus)return;setBusy(true);try{await invoke("transitionEggStatus",{eggId:egg.eggId,targetStatus});setMessage("บันทึกสถานะไข่สำเร็จ");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};return options.length?<form className="card" onSubmit={submit}><h6>บันทึกผลไข่</h6><label className="field">สถานะ<select aria-label="สถานะไข่ใหม่" value={targetStatus} onChange={event=>setTargetStatus(event.target.value)}><option value="">เลือกสถานะ</option>{options.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button disabled={busy}>{busy?"กำลังบันทึก…":"บันทึกสถานะ"}</button>{message&&<p role="status">{message}</p>}</form>:null;}
function CycleTransition({cycle,onChanged}:{cycle:Row;onChanged:()=>Promise<void>}){const [target,setTarget]=useState<"closed"|"cancelled">("closed"),[date,setDate]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const submit=async(event:FormEvent)=>{event.preventDefault();const endedOn=thaiDisplayToIso(date);if(!endedOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{await invoke(target==="closed"?"closeBreedingCycle":"cancelBreedingCycle",{breedingCycleId:cycle.breedingCycleId,endedOn});setMessage("อัปเดตรอบเพาะสำเร็จ");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};return cycle.status==="active"?<form className="card" onSubmit={submit}><h5>ปิดรอบเพาะ</h5><label className="field">การดำเนินการ<select aria-label="การดำเนินการรอบเพาะ" value={target} onChange={event=>setTarget(event.target.value as "closed"|"cancelled")}><option value="closed">ปิดรอบเพาะ</option><option value="cancelled">ยกเลิกรอบเพาะ</option></select></label><label className="field">วันที่สิ้นสุด *<input required aria-label="วันที่สิ้นสุดรอบเพาะ" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event=>changeThaiDate(event.target.value,setDate)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"ยืนยัน"}</button>{message&&<p role="status">{message}</p>}</form>:null;}
function EggDetail({ egg, cycle, pair, onBack, onChanged }: { egg: Row; cycle: Row; pair: Row; onBack: () => void; onChanged: () => Promise<void> }) {
  const father=pairMember(pair,"male"),mother=pairMember(pair,"female"),assignments=Array.isArray(pair.assignments)?pair.assignments as Row[]:[],cage=assignments.find(assignment=>!assignment.endsOn)??assignments.at(-1);
  return <section className="card"><button type="button" onClick={onBack}>กลับไปรายการไข่</button><h5>Egg Detail</h5><p>ลำดับไข่: {label(egg.sequenceNo)}</p><p>วันที่ไข่: {isoToThaiDisplay(egg.laidOn)||"-"}</p><p>Status: {label(egg.status)}</p><p>รอบเพาะ: {isoToThaiDisplay(cycle.startedOn)||"-"} · {label(cycle.status)}</p><p>พ่อ: {label(father?.displayName)} · Ring ID: {label(father?.ringId)}</p><p>แม่: {label(mother?.displayName)} · Ring ID: {label(mother?.ringId)}</p><p>กรง: {cage?`${label(cage.code)} / ${label(cage.name)}`:"-"}</p>{["laid","fertile"].includes(String(egg.status))&&<HatchEggForm egg={egg} onChanged={onChanged}/>}<EggStatusAction egg={egg} onChanged={onChanged}/>{egg.status==="hatched"&&<p className="muted">ไข่ฟักแล้ว</p>}</section>;
}

function BreedingCycles({ pair, onChanged }: { pair: Row; onChanged: () => Promise<void> }) {
  const cycles=Array.isArray(pair.cycles)?pair.cycles as Row[]:[]; const [selectedId,setSelectedId]=useState<string|null>(null); const [selectedEggId,setSelectedEggId]=useState<string|null>(null); const [dateText,setDateText]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const selected=cycles.find(cycle=>cycle.breedingCycleId===selectedId)??null; const selectedEgg=selected&&Array.isArray(selected.eggs)?(selected.eggs as Row[]).find(egg=>egg.eggId===selectedEggId)??null:null; const father=pairMember(pair,"male"),mother=pairMember(pair,"female"),assignments=Array.isArray(pair.assignments)?pair.assignments as Row[]:[],cage=assignments.find(assignment=>!assignment.endsOn);
  const submit=async(event:FormEvent)=>{event.preventDefault();const startedOn=thaiDisplayToIso(dateText);if(!startedOn){setMessage("กรุณากรอกวันที่ที่มีอยู่จริง");return;}setBusy(true);try{const result=await invoke("createBreedingCycle",{pairId:pair.pairId,startedOn}) as Row;setSelectedId(String(result.breedingCycleId));setMessage("สร้างรอบเพาะสำเร็จ");setDateText("");await onChanged();}catch(error){setMessage(thaiError(error));}finally{setBusy(false);}};
  return <section className="breeding-cycles"><header className="breeding-thread-heading"><small>BREEDING THREAD</small><h4>รอบเพาะและไข่</h4><p>กิจกรรมเพาะของคู่นี้ เรียงจากรอบเพาะไปยังไข่ที่บันทึกไว้</p></header><div className="breeding-cycle-layout"><div className="cycle-ledger">{cycles.length?cycles.map((cycle,index)=><button type="button" className="breeding-cycle-row" key={cycle.breedingCycleId} onClick={()=>{setSelectedId(String(cycle.breedingCycleId));setSelectedEggId(null);}}><span className="cycle-sequence">{String(index+1).padStart(2,"0")}</span><span><b>รอบเพาะ</b><small>เริ่ม: {isoToThaiDisplay(cycle.startedOn)||"-"}</small></span><span>สถานะ: {label(cycle.status)}</span><span className="cycle-egg-count">ไข่: <b>{Array.isArray(cycle.eggs)?cycle.eggs.length:0}</b></span><span className="cycle-open">ดู →</span></button>):<p className="muted">ยังไม่มีรอบเพาะ</p>}</div>{pair.status==="active"&&<form className="card breeding-cycle-form" onSubmit={submit}><small>RECORD ACTIVITY</small><h5>สร้างรอบเพาะ</h5><p>พ่อนก: {label(father?.displayName)} · Ring ID: {label(father?.ringId)}</p><p>แม่นก: {label(mother?.displayName)} · Ring ID: {label(mother?.ringId)}</p><p>กรงปัจจุบัน: {cage?`${label(cage.code)} / ${label(cage.name)}`:"-"}</p><p>สถานะคู่: {label(pair.status)}</p><label className="field">วันเริ่ม *<input required aria-label="วันเริ่มรอบเพาะ" placeholder="DD/MM/YYYY" inputMode="numeric" value={dateText} onChange={event=>changeThaiDate(event.target.value,setDateText)}/></label><button disabled={busy}>{busy?"กำลังบันทึก…":"สร้างรอบเพาะ"}</button>{message&&<p role="status">{message}</p>}</form>}</div>{selected&&(selectedEgg?<EggDetail egg={selectedEgg} cycle={selected} pair={pair} onBack={()=>setSelectedEggId(null)} onChanged={onChanged}/>:<section className="breeding-cycle-selected"><header><small>CYCLE CHAPTER</small><h5>รอบเพาะที่เลือก</h5><span>เริ่ม: {isoToThaiDisplay(selected.startedOn)||"-"} · สถานะ: {label(selected.status)} · ไข่: {Array.isArray(selected.eggs)?selected.eggs.length:0}</span></header><div className="egg-ledger">{Array.isArray(selected.eggs)&&selected.eggs.map((egg:Row)=><button type="button" className="breeding-egg-row" key={egg.eggId} onClick={()=>setSelectedEggId(String(egg.eggId))}><i aria-hidden="true"/>ไข่ลำดับ {egg.sequenceNo} · {isoToThaiDisplay(egg.laidOn)||"-"} · {label(egg.status)}<b>ดู →</b></button>)}</div><EggForm cycle={selected} pair={pair} onChanged={onChanged}/></section>)}</section>;
}

function PairDetail({ data, cages, onChanged }: { data: Row; cages: Row[]; onChanged: () => Promise<void> }) { const [actionMessage,setActionMessage]=useState(""); const father=pairMember(data,"male"),mother=pairMember(data,"female"),assignments=Array.isArray(data.assignments)?data.assignments as Row[]:[],cycles=Array.isArray(data.cycles)?data.cycles as Row[]:[],openAssignment=assignments.find(assignment=>!assignment.endsOn),currentCycle=cycles.find(cycle=>cycle.status==="active")??cycles[0]; return <div className="breeding-pair-detail"><header className="breeding-pair-anchor"><div className="breeding-pair-title"><div><small>THE BREEDING THREAD</small><h2>{label(father?.displayName)} × {label(mother?.displayName)}</h2><p>วันเริ่ม: {isoToThaiDisplay(data.startedOn)||"-"}</p></div><StatusBadge status={data.status}/></div><PairRelationship leftName={label(father?.displayName)} leftIdentifier={label(father?.ringId)} rightName={label(mother?.displayName)} rightIdentifier={label(mother?.ringId)}/></header><section className="breeding-context"><header><small>BREEDING CONTEXT</small><h3>กรงปัจจุบัน</h3></header>{assignments.length?<div className="cage-context-list">{assignments.map((assignment,index)=><p key={index}><strong>{label(assignment.name)}</strong><span>Code: {label(assignment.code)}</span><small>{isoToThaiDisplay(assignment.startsOn)||"-"} — {isoToThaiDisplay(assignment.endsOn)||"ปัจจุบัน"}</small></p>)}</div>:<EmptyState title="ยังไม่ได้จัดเข้ากรง"/>}{currentCycle&&<aside className="cycle-context-preview"><small>รอบเพาะปัจจุบัน</small><strong>{isoToThaiDisplay(currentCycle.startedOn)||"-"}</strong><span>{label(currentCycle.status)} · ไข่ {Array.isArray(currentCycle.eggs)?currentCycle.eggs.length:0}</span></aside>}</section><div className="breeding-record-zone">{data.status==="draft"&&<PairActivation pairId={String(data.pairId)} onChanged={onChanged} onSuccess={setActionMessage}/>} {data.status==="inactive"&&<PairReactivation pairId={String(data.pairId)} onChanged={onChanged}/>} {data.status==="active"&&!openAssignment&&<CageAssignment pairId={String(data.pairId)} cages={cages} onChanged={onChanged} onSuccess={setActionMessage}/>} {data.status==="active"&&openAssignment&&<><AssignmentMove pairId={String(data.pairId)} cages={cages} onChanged={onChanged}/><AssignmentEnd assignment={openAssignment} onChanged={onChanged}/><PairLifecycle pairId={String(data.pairId)} onChanged={onChanged}/></>}</div>{data.status==="active"&&<BreedingCycles pair={data} onChanged={onChanged}/>} {currentCycle&&<CycleTransition cycle={currentCycle} onChanged={onChanged}/>} {actionMessage&&<p role="status">{actionMessage}</p>}</div>; }
function BreedingWorkspace({pairs,cages,birds,refresh}:{pairs:Row[];cages:Row[];birds:Row[];refresh:()=>void}) {
  const [creation,setCreation]=useState<"cage"|"pair"|null>(null);
  const [pairOpen,setPairOpen]=useState(false);
  return <>
    <div className={pairOpen?"pair-focus":"content-grid"}>
      <DetailList title="คู่เพาะ" rows={pairs} idKey="pairId" operation="getPairDetails" cages={cages} onDetailChange={setPairOpen}/>
      {!pairOpen&&<DetailList title="กรง" rows={cages} idKey="cageId"/>}
    </div>
    {!pairOpen&&<section className="form-zone breeding-actions" aria-label="สร้างข้อมูลเพาะพันธุ์"><div><h2>สร้างข้อมูลเพาะพันธุ์</h2><p className="muted">เลือกงานที่ต้องการ ระบบจะแสดงแบบฟอร์มเฉพาะรายการนั้น</p></div><div className="quick-actions"><button type="button" aria-expanded={creation==="cage"} onClick={()=>setCreation(current=>current==="cage"?null:"cage")}>เพิ่มกรง</button><button type="button" aria-expanded={creation==="pair"} onClick={()=>setCreation(current=>current==="pair"?null:"pair")}>สร้างคู่</button>{creation&&<button type="button" className="secondary-action" onClick={()=>setCreation(null)}>ปิดแบบฟอร์ม</button>}</div>{creation&&<div className="creation-panel">{creation==="cage"?<Form title="เพิ่มกรง" operation="createCage" fields={[["code","รหัส","text",true],["name","ชื่อ","text",true],["status","สถานะ","text",true]]} refresh={refresh}/>:<PairForm birds={birds} refresh={refresh}/>}</div>}</section>}
  </>;
}

export function App() {
  const [page, setPage] = useState<Page>("Dashboard"); const [data, setData] = useState<Record<string, Row[]>>({}); const [summary, setSummary] = useState<Row | null>(null); const [error, setError] = useState("");
  const refresh = async () => { const names = ["listBirds", "listCages", "listPairs", "listBreedingCycles", "listEggs", "listCustomers", "listReservations", "listPayments", "listRefunds", "listSales", "listGiveaways", "listDeliveries", "listHandovers", "listEligibleCompletedSales"]; try { const result = await Promise.all(names.map(n => invoke(n, { limit: n === "listBirds" ? 50 : 25 }) as Promise<Row[]>)); setData(Object.fromEntries(names.map((n, i) => [n, result[i]]))); setSummary(await invoke("getDashboardSummary", {}) as Row); } catch (caught) { setError(thaiError(caught)); } };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if(page!=="Birds")return; void (async()=>{try{const birds=await invoke("listBirds",{limit:50}) as Row[];setData(current=>({...current,listBirds:birds}));}catch(caught){setError(thaiError(caught));}})(); }, [page]);
  const f = (title: string, operation: string, fields: FormField[]) => <Form title={title} operation={operation} fields={fields} refresh={refresh} initialValues={operation === "createExternalBird" ? { origin: "external" } : {}} resetOnSuccess={operation === "createExternalBird"||operation==="createCustomer"}/>;
  return <div className="app"><aside className="nav"><div className="brand">Birds My Boss<small className="muted">Farm System V1</small></div>{pages.map(p => <button key={p} className={page === p ? "active" : ""} aria-current={page===p?"page":undefined} onClick={() => setPage(p)}>{p}</button>)}</aside><main>{error && <p role="alert">{error}</p>}
    {page === "Dashboard" && <Dashboard data={data} summary={summary} navigate={setPage}/>}
    {page === "Birds" && <><PageHeader title="ทะเบียนนก" subtitle="ค้นหา ดูประวัติ และจัดการข้อมูลนกในฟาร์ม"/><DetailList title="นกทั้งหมด" rows={data.listBirds ?? []} idKey="birdId" operation="getBirdDetails"/><div className="form-zone"><h2>งานบันทึกข้อมูล</h2><div className="form-grid">{f("ตรวจสอบ Ring ID", "checkRingIdAvailability", [["ringId", "Ring ID", "text", true]])}{f("เพิ่มนกจากภายนอก", "createExternalBird", [["ringId", "Ring ID", "text", true], ["displayName", "ชื่อ", "text", true], ["origin", "แหล่งที่มา", "select", true, ["external", "purchased", "rescued", "unknown"]], ["hatchedOn", "วันฟัก/วันเกิด", "date", false], ["mutation", "Mutation/สี", "text", false]])}</div></div></>}
    {page === "Breeding" && <><PageHeader title="การเพาะพันธุ์" subtitle="จัดการกรง คู่เพาะ รอบเพาะ และไข่ตามลำดับงานจริง"/><BreedingWorkspace pairs={data.listPairs??[]} cages={data.listCages??[]} birds={data.listBirds??[]} refresh={refresh}/></>}
    {page === "Customers" && <><PageHeader title="ลูกค้า" subtitle="บุคคลและความสัมพันธ์ที่บันทึกไว้อย่างน่าเชื่อถือกับฟาร์ม"/><Customers customers={data.listCustomers ?? []} birds={data.listBirds ?? []} createForm={f("เพิ่มลูกค้า", "createCustomer", [["displayName", "ชื่อผู้ติดต่อ", "text", true], ["phone", "โทรศัพท์", "text", false], ["email", "อีเมล", "text", false]])}/></>}
    {page === "Sales" && <><PageHeader title="การขาย" subtitle="Reservation, Payment, Refund และ Sale ใน workflow เดียว"/><Commercial birds={data.listBirds??[]} customers={data.listCustomers??[]} reservations={data.listReservations??[]} payments={data.listPayments??[]} refunds={data.listRefunds??[]} sales={data.listSales??[]} deliveries={data.listDeliveries??[]} handovers={data.listHandovers??[]} onRefresh={refresh}/></>}
    {page === "Giveaways" && <Giveaways giveaways={data.listGiveaways??[]} birds={data.listBirds??[]} customers={data.listCustomers??[]} onRefresh={refresh}/>}
    {page === "Delivery & Handover" && <><PageHeader title="จัดส่งและส่งมอบ" subtitle="ติดตามค่าจัดส่งและส่งมอบนกจากข้อมูลการขาย"/><DeliveryHandover eligibleSales={data.listEligibleCompletedSales??[]} birds={data.listBirds??[]} customers={data.listCustomers??[]} payments={data.listPayments??[]} deliveries={data.listDeliveries??[]} handovers={data.listHandovers??[]} onRefresh={refresh}/></>}
    {page === "Passport" && <><PageHeader title="Passport Admin" subtitle="เผยแพร่ข้อมูลนกอย่างปลอดภัยด้วยลิงก์และ QR"/><PassportWorkflow birds={data.listBirds??[]} handovers={data.listHandovers??[]} onRefresh={refresh}/></>}
  </main></div>;
}
