import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { Commercial } from "./Commercial";

const mocks=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock("./functions",()=>({invoke:mocks.invoke,thaiError:()=>"บันทึกไม่สำเร็จ"}));

const birds=[{birdId:"bird-secret-1",ringId:"TH-001",displayName:"Sunny",mutation:"Lutino",currentSex:"male",status:"active",origin:"farm_hatched"},{birdId:"bird-secret-2",ringId:"TH-002",displayName:"Moon",mutation:"Normal",currentSex:"female",status:"active",origin:"external"}];
const customers=[{customerId:"customer-secret-1",displayName:"สมชาย",phone:"0812345678",email:"somchai@example.com",status:"active"}];
const reservations=[{reservationId:"reservation-secret-1",birdId:"bird-secret-1",customerId:"customer-secret-1",reservedOn:"2026-08-14",expiresOn:"2026-08-20",status:"active"}];
const payments=[{paymentId:"payment-secret-1",reservationId:"reservation-secret-1",amount:1000,currency:"THB",receivedOn:"2026-08-14",paymentMethod:"transfer",status:"received"}];
const refunds=[{refundId:"refund-secret-1",paymentId:"payment-secret-1",amount:100,outcome:"partial_refund",refundedOn:"2026-08-15",reason:"adjustment"}];
const sales=[{saleId:"sale-secret-1",birdId:"bird-secret-2",customerId:"customer-secret-1",status:"draft",createdOn:"2026-08-14"}];
const props={birds,customers,reservations,payments,refunds,sales,onRefresh:vi.fn()};

afterEach(()=>{cleanup();vi.clearAllMocks();});

it("presents human contexts and conceals canonical IDs",()=>{render(<Commercial {...props}/>);expect(screen.getAllByText(/Sunny/).length).toBeGreaterThan(0);expect(screen.getAllByText(/สมชาย/).length).toBeGreaterThan(0);expect(screen.getAllByText(/14\/08\/2026/).length).toBeGreaterThan(0);for(const id of ["bird-secret-1","customer-secret-1","reservation-secret-1","payment-secret-1","sale-secret-1"])expect(screen.queryByText(id)).toBeNull();});

it("distinguishes Customer from Orange Ring Bird identity and shows only trusted related records",()=>{const completed=[{...sales[0],status:"completed",completedOn:"2026-08-18"}],deliveries=[{deliveryId:"delivery-secret",saleId:"sale-secret-1",distanceKm:14,shippingFee:120,currency:"THB",createdOn:"2026-08-18",status:"planned"}],handovers=[{handoverId:"handover-secret",saleId:"sale-secret-1",birdId:"bird-secret-2",handoverOn:"2026-08-19",recipientSnapshot:{name:"สมชาย"},status:"completed"}];const {container}=render(<Commercial {...props} sales={completed} deliveries={deliveries} handovers={handovers}/>);const sale=screen.getByRole("button",{name:/สมชาย.*Moon.*Ring ID: TH-002.*Completed/});expect(within(sale).getByText("CUSTOMER")).toBeTruthy();expect(sale.querySelectorAll(".orange-ring")).toHaveLength(1);fireEvent.click(sale);expect(screen.getByText("120 THB")).toBeTruthy();expect(screen.getByText(/19\/08\/2026.*สมชาย/)).toBeTruthy();expect(container.textContent).not.toContain("delivery-secret");expect(container.textContent).not.toContain("handover-secret");expect(screen.queryByText(/ยอดคงเหลือการขาย|เปอร์เซ็นต์ชำระ/)).toBeNull();});

it("uses a restrained canonical status and truthful Commercial Ledger language",()=>{const salePayment={paymentId:"sale-payment-secret",saleId:"sale-secret-1",amount:3500,currency:"THB",receivedOn:"2026-08-14",paymentMethod:"cash",status:"received"};const {container}=render(<Commercial {...props} payments={[...payments,salePayment]}/>);expect(screen.getByText("การชำระเงิน 1 รายการ")).toBeTruthy();expect(container.textContent).not.toMatch(/ชำระครบ|paid in full|settled/i);fireEvent.click(screen.getByRole("button",{name:/Moon.*14\/08\/2026/}));const hero=container.querySelector(".sale-detail-hero")!;expect(hero.querySelector(".status-badge")?.textContent).toBe("แบบร่าง");expect(hero.querySelector(".sale-status-orb")).toBeNull();const ledger=container.querySelector(".commercial-ledger") as HTMLElement,paymentRow=ledger.querySelector(".commercial-ledger-row") as HTMLElement;expect(within(paymentRow).getByText("3500 THB")).toBeTruthy();expect(within(paymentRow).getByText("14/08/2026")).toBeTruthy();expect(within(paymentRow).getByText("เงินสด")).toBeTruthy();expect(within(paymentRow).getByText("รับเงินแล้ว")).toBeTruthy();});

it.each([["cash","เงินสด"],["transfer","โอนเงิน / พร้อมเพย์"],["card","บัตรเครดิต/เดบิต"],["other","อื่น ๆ"]])("submits canonical payment method %s for %s",async(method,label)=>{mocks.invoke.mockResolvedValue({paymentId:"new-payment"});render(<Commercial {...props}/>);fireEvent.click(screen.getByRole("button",{name:/Sunny.*14\/08\/2026/}));const form=screen.getByRole("heading",{name:"รับชำระเงิน"}).closest("form")!;const select=within(form).getByLabelText("วิธีชำระเงิน") as HTMLSelectElement;expect((within(select).getByRole("option",{name:label}) as HTMLOptionElement).value).toBe(method);fireEvent.change(within(form).getByLabelText("จำนวนเงิน"),{target:{value:"250"}});fireEvent.change(select,{target:{value:method}});fireEvent.change(within(form).getByLabelText("วันที่รับเงิน"),{target:{value:"16082026"}});fireEvent.submit(form);expect(mocks.invoke).toHaveBeenCalledWith("recordPayment",{reservationId:"reservation-secret-1",amount:250,currency:"THB",paymentMethod:method,receivedOn:"2026-08-16"});});

it("keeps Reservation semantically separate with its own date, expiry, and status",()=>{const {container}=render(<Commercial {...props}/>);const reservation=screen.getByRole("button",{name:/Sunny.*สมชาย/});expect(within(reservation).getByText("จอง 14/08/2026")).toBeTruthy();expect(within(reservation).getByText("หมดอายุ 20/08/2026")).toBeTruthy();expect(within(reservation).getByText("กำลังจอง")).toBeTruthy();expect(container.querySelector(".reservation-registry .sale-passage-link")).toBeNull();});

it("shows only active unconverted Reservations in the work queue",()=>{const variants=[reservations[0],{...reservations[0],reservationId:"cancelled",status:"cancelled"},{...reservations[0],reservationId:"expired",status:"expired"}];const {container}=render(<Commercial {...props} reservations={variants}/>);const reservationForm=screen.getByRole("heading",{name:"สร้างการจอง"}).closest("form")!;expect(within(reservationForm).getAllByRole("option",{name:/สมชาย.*ใช้งานอยู่/}).length).toBeGreaterThan(0);const queue=container.querySelector(".reservation-registry") as HTMLElement;expect(within(queue).getByText("กำลังจอง")).toBeTruthy();expect(within(queue).queryByText("ยกเลิกการจอง")).toBeNull();expect(within(queue).queryByText("การจองหมดอายุ")).toBeNull();fireEvent.click(within(queue).getByRole("button",{name:/Sunny.*สมชาย/}));expect(screen.getByText("สถานะ: กำลังจอง")).toBeTruthy();});

it("creates a reservation from selected contexts and canonicalizes dates",async()=>{const onRefresh=vi.fn();mocks.invoke.mockResolvedValue({reservationId:"new"});render(<Commercial {...props} reservations={[]} onRefresh={onRefresh}/>);const reservationForm=screen.getByRole("heading",{name:"สร้างการจอง"}).closest("form")!;fireEvent.click(within(reservationForm).getByRole("option",{name:/TH-001/}));fireEvent.click(within(reservationForm).getByRole("option",{name:/สมชาย/}));fireEvent.change(within(reservationForm).getByLabelText("วันที่จอง"),{target:{value:"14082026"}});fireEvent.change(within(reservationForm).getByLabelText("วันหมดอายุ"),{target:{value:"20082026"}});fireEvent.submit(reservationForm);expect(mocks.invoke).toHaveBeenCalledWith("createReservation",{birdId:"bird-secret-1",customerId:"customer-secret-1",reservedOn:"2026-08-14",expiresOn:"2026-08-20"});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(1));});

it("captures optional THB agreement snapshots and keeps reservation conversion read-only",async()=>{const onRefresh=vi.fn();mocks.invoke.mockResolvedValue({reservationId:"new"});render(<Commercial {...props} reservations={[]} onRefresh={onRefresh}/>);const reservationForm=screen.getByRole("heading",{name:"สร้างการจอง"}).closest("form")!;fireEvent.click(within(reservationForm).getByRole("option",{name:/TH-001/}));fireEvent.click(within(reservationForm).getByRole("option",{name:/สมชาย/}));fireEvent.change(within(reservationForm).getByLabelText("วันที่จอง"),{target:{value:"14082026"}});fireEvent.change(within(reservationForm).getByLabelText("ราคาที่ตกลงสำหรับการจอง"),{target:{value:"1250.5"}});fireEvent.submit(reservationForm);expect(mocks.invoke).toHaveBeenCalledWith("createReservation",{birdId:"bird-secret-1",customerId:"customer-secret-1",reservedOn:"2026-08-14",agreedPrice:1250.5,currency:"THB"});const priced=[{...reservations[0],agreedPrice:1250.5,currency:"THB"}];render(<Commercial {...props} reservations={priced}/>);fireEvent.click(screen.getAllByRole("button",{name:/Sunny.*สมชาย/})[0]);expect(screen.getByText(/1250.5 THB/)).toBeTruthy();const conversion=screen.getByRole("heading",{name:"สร้างการขายจากการจอง"}).closest("form")!;expect(within(conversion).queryByLabelText("ราคาที่ตกลงสำหรับการขาย")).toBeNull();});

it("requires and submits a THB sale price when the linked Reservation has no snapshot",async()=>{const onRefresh=vi.fn();mocks.invoke.mockResolvedValue({saleId:"new-sale"});render(<Commercial {...props} onRefresh={onRefresh}/>);fireEvent.click(screen.getByRole("button",{name:/Sunny.*14\/08\/2026/}));const conversion=screen.getByRole("heading",{name:"สร้างการขายจากการจอง"}).closest("form")!;const price=within(conversion).getByLabelText("ราคาที่ตกลงสำหรับการขาย") as HTMLInputElement;expect(price.required).toBe(true);expect(conversion.textContent).toContain("ราคาที่ตกลง (THB) *");fireEvent.change(within(conversion).getByLabelText("วันที่สร้างการขาย"),{target:{value:"09092026"}});fireEvent.submit(conversion);expect(within(conversion).getByText("ราคาที่ตกลงต้องมากกว่าศูนย์")).toBeTruthy();expect(mocks.invoke).not.toHaveBeenCalled();fireEvent.change(price,{target:{value:"0"}});fireEvent.submit(conversion);expect(mocks.invoke).not.toHaveBeenCalled();fireEvent.change(price,{target:{value:"1000"}});fireEvent.submit(conversion);expect(mocks.invoke).toHaveBeenCalledWith("createSale",{birdId:"bird-secret-1",customerId:"customer-secret-1",reservationId:"reservation-secret-1",agreedPrice:1000,currency:"THB",createdOn:"2026-09-09"});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(1));});

it("opens a converted Reservation Sale as confirmed with Close Sale available",()=>{const converted=[{...sales[0],birdId:"bird-secret-1",reservationId:"reservation-secret-1",status:"confirmed",agreedPrice:1000,currency:"THB"}];const {container}=render(<Commercial {...props} sales={converted}/>);fireEvent.click(screen.getByRole("button",{name:/Sunny.*ยืนยันแล้ว/}));expect(container.querySelector(".sale-detail-hero .status-badge")?.textContent).toBe("ยืนยันแล้ว");expect(screen.queryByRole("button",{name:"ยืนยันการขาย"})).toBeNull();expect(screen.getByRole("heading",{name:"ปิดการขาย"})).toBeTruthy();expect(screen.getByRole("button",{name:"ปิดการขาย"})).toBeTruthy();});

it("removes a converted Reservation from the queue and preserves Sale provenance",()=>{const converted=[{...sales[0],birdId:"bird-secret-1",reservationId:"reservation-secret-1",status:"confirmed",agreedPrice:1000,currency:"THB"}];const {container}=render(<Commercial {...props} sales={converted}/>);const queue=container.querySelector(".reservation-registry") as HTMLElement;expect(within(queue).queryByRole("button",{name:/Sunny.*สมชาย/})).toBeNull();expect(within(queue).getByText("ไม่มีการจองที่กำลังดำเนินการ")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/Sunny.*ยืนยันแล้ว/}));expect(screen.getByText(/สร้างจากการจองวันที่ 14\/08\/2026/)).toBeTruthy();expect(screen.getByText(/วันหมดอายุเดิม 20\/08\/2026/)).toBeTruthy();});

it("includes the Reservation deposit in a fully paid Sale and hides payment entry",()=>{const converted=[{...sales[0],birdId:"bird-secret-1",reservationId:"reservation-secret-1",status:"confirmed",agreedPrice:1000,currency:"THB"}],combined=[{...payments[0],amount:200},{paymentId:"sale-payment",saleId:"sale-secret-1",amount:800,currency:"THB",receivedOn:"2026-09-09",paymentMethod:"cash",status:"received"}];const {container}=render(<Commercial {...props} sales={converted} payments={combined} refunds={[]}/>);fireEvent.click(screen.getByRole("button",{name:/Sunny.*ยืนยันแล้ว/}));const summary=container.querySelector(".commercial-ledger > .sales-truth-note")!;expect(summary.textContent).toContain("รับชำระสุทธิ: 1000 THB");expect(summary.textContent).toContain("คงเหลือ: 0 THB");expect(screen.getByText("ชำระครบแล้ว")).toBeTruthy();expect(screen.queryByRole("heading",{name:"รับชำระเงิน"})).toBeNull();expect(screen.getAllByText("รับเงินแล้ว")).toHaveLength(2);});

it("reopens the Sale balance after a refund and blocks frontend overpayment",()=>{const converted=[{...sales[0],birdId:"bird-secret-1",reservationId:"reservation-secret-1",status:"confirmed",agreedPrice:1000,currency:"THB"}],combined=[{...payments[0],amount:200},{paymentId:"sale-payment",saleId:"sale-secret-1",amount:800,currency:"THB",receivedOn:"2026-09-09",paymentMethod:"cash",status:"received"}],saleRefunds=[{refundId:"sale-refund",paymentId:"sale-payment",amount:100,outcome:"partial_refund",refundedOn:"2026-09-10",reason:"adjustment"}];const {container}=render(<Commercial {...props} sales={converted} payments={combined} refunds={saleRefunds}/>);fireEvent.click(screen.getByRole("button",{name:/Sunny.*ยืนยันแล้ว/}));expect(container.querySelector(".commercial-ledger > .sales-truth-note")?.textContent).toContain("คงเหลือ: 100 THB");const form=screen.getByRole("heading",{name:"รับชำระเงิน"}).closest("form")!;fireEvent.change(within(form).getByLabelText("จำนวนเงิน"),{target:{value:"101"}});fireEvent.change(within(form).getByLabelText("วิธีชำระเงิน"),{target:{value:"cash"}});fireEvent.change(within(form).getByLabelText("วันที่รับเงิน"),{target:{value:"11092026"}});fireEvent.submit(form);expect(within(form).getByText("จำนวนเงินต้องไม่เกินยอดคงเหลือ 100 THB")).toBeTruthy();expect(mocks.invoke.mock.calls.some(([operation])=>operation==="recordPayment")).toBe(false);});

it("records payment and refund from selected reservation and payment contexts",async()=>{mocks.invoke.mockResolvedValue({});const onRefresh=vi.fn();render(<Commercial {...props} onRefresh={onRefresh}/>);fireEvent.click(screen.getByRole("button",{name:/Sunny.*14\/08\/2026/}));const paymentForm=screen.getByRole("heading",{name:"รับชำระเงิน"}).closest("form")!;fireEvent.change(within(paymentForm).getByLabelText("จำนวนเงิน"),{target:{value:"250"}});fireEvent.change(within(paymentForm).getByLabelText("วิธีชำระเงิน"),{target:{value:"cash"}});fireEvent.change(within(paymentForm).getByLabelText("วันที่รับเงิน"),{target:{value:"16082026"}});fireEvent.submit(paymentForm);expect(mocks.invoke).toHaveBeenCalledWith("recordPayment",{reservationId:"reservation-secret-1",amount:250,currency:"THB",paymentMethod:"cash",receivedOn:"2026-08-16"});fireEvent.click(screen.getByRole("button",{name:/1000 THB/}));const refundForm=screen.getByRole("heading",{name:"คืนเงิน"}).closest("form")!;expect(within(refundForm).getByText(/คงเหลือ: 900/)).toBeTruthy();fireEvent.change(within(refundForm).getByLabelText("รูปแบบคืนเงิน"),{target:{value:"partial_refund"}});fireEvent.change(within(refundForm).getByLabelText("จำนวนเงินคืน"),{target:{value:"200"}});fireEvent.change(within(refundForm).getByLabelText("เหตุผลคืนเงิน"),{target:{value:"customer request"}});fireEvent.change(within(refundForm).getByLabelText("วันที่คืนเงิน"),{target:{value:"17082026"}});fireEvent.submit(refundForm);expect(mocks.invoke).toHaveBeenCalledWith("refundPayment",{paymentId:"payment-secret-1",outcome:"partial_refund",amount:200,reason:"customer request",refundedOn:"2026-08-17"});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(2));});

it("creates, confirms, and closes sales using internal selected IDs, preserving failed input",async()=>{mocks.invoke.mockResolvedValue({saleId:"new-sale"});const onRefresh=vi.fn();const view=render(<Commercial {...props} onRefresh={onRefresh}/>);const direct=screen.getByRole("heading",{name:"สร้างการขายโดยตรง"}).closest("form")!;fireEvent.click(within(direct).getByRole("option",{name:/TH-001/}));fireEvent.click(within(direct).getByRole("option",{name:/สมชาย/}));fireEvent.change(within(direct).getByLabelText("วันที่สร้างการขาย"),{target:{value:"14082026"}});fireEvent.submit(direct);expect(mocks.invoke).toHaveBeenCalledWith("createSale",{birdId:"bird-secret-1",customerId:"customer-secret-1",createdOn:"2026-08-14"});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(1));fireEvent.click(screen.getByRole("button",{name:/Moon.*14\/08\/2026/}));fireEvent.click(screen.getByRole("button",{name:"ยืนยันการขาย"}));expect(mocks.invoke).toHaveBeenCalledWith("confirmSale",{saleId:"sale-secret-1"});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(2));view.rerender(<Commercial {...props} sales={[{...sales[0],status:"confirmed"}]} onRefresh={onRefresh}/>);mocks.invoke.mockRejectedValueOnce(new Error("failed"));const close=screen.getByRole("heading",{name:"ปิดการขาย"}).closest("form")!;const date=within(close).getByLabelText("วันที่ปิดการขาย") as HTMLInputElement;fireEvent.change(date,{target:{value:"18082026"}});fireEvent.submit(close);expect(mocks.invoke).toHaveBeenCalledWith("completeSale",{saleId:"sale-secret-1",completedOn:"2026-08-18"});expect(date.value).toBe("18/08/2026");expect(onRefresh).toHaveBeenCalledTimes(2);});

it("renders operator-only chronological Sale Timeline without exposing payload",async()=>{mocks.invoke.mockImplementation(async(operation:string)=>operation==="listSaleTimeline"?[{saleTimelineId:"timeline-secret",eventType:"sale_created",occurredAt:"2026-08-14"}]:{});const {container}=render(<Commercial {...props}/>);fireEvent.click(screen.getByRole("button",{name:/Moon.*14\/08\/2026/}));expect(await screen.findByText("sale_created")).toBeTruthy();expect(container.textContent).not.toContain("timeline-secret");});
