import { FormEvent, useMemo, useState } from "react";
import { OrangeRing, ProvenanceMarker, TrustMarker } from "./bmb-design-system";
import { isoToThaiDisplay, parseThaiDisplayDate, thaiDisplayToIso } from "./date";
import { invoke, thaiError } from "./functions";
import { displayValue } from "./presentation";
import "./DeliveryHandover.css";

type Row = Record<string, any>;
type Refresh = () => Promise<void> | void;
const show = displayValue;
const changeDate = (raw: string, set: (value: string) => void) => { const value = raw.replace(/\D/g, "").slice(0, 8); set(value.length === 8 ? parseThaiDisplayDate(value) ?? value : value); };

function BirdIdentity({ bird, sold = false }: { bird?: Row; sold?: boolean }) {
  if (!bird) return <p className="final-passage-missing">ไม่พบข้อมูลนกในรายการอ่านที่เชื่อถือได้</p>;
  return <div className="final-passage-bird"><OrangeRing variant="selected"/><span><small>BIRD IDENTITY</small><strong>{show(bird.displayName)}</strong><em>Ring ID: {show(bird.ringId)}</em>{bird.mutation && <i>{show(bird.mutation)}</i>}</span>{sold && bird.status === "sold" && <ProvenanceMarker>Sold</ProvenanceMarker>}</div>;
}

function CustomerContext({ customer }: { customer?: Row }) {
  return customer ? <div className="final-passage-customer"><small>TRUSTED KEEPER</small><strong>{show(customer.displayName)}</strong><span>{show(customer.phone)}</span><span>{show(customer.email)}</span></div> : <span className="final-passage-missing">ไม่พบข้อมูลลูกค้า</span>;
}

function RecipientSnapshot({ recipient }: { recipient?: Row }) {
  return <div className="recipient-snapshot"><small>RECIPIENT SNAPSHOT</small><strong>{show(recipient?.name)}</strong>{recipient?.phone && <span>{show(recipient.phone)}</span>}{recipient?.address && <span>{show(recipient.address)}</span>}</div>;
}

function SaleContext({ sale, bird, customer, payments, compact = false }: { sale: Row; bird?: Row; customer?: Row; payments: Row[]; compact?: boolean }) {
  const linked = payments.filter(payment => payment.saleId === sale.saleId);
  return <section className={`final-passage-context${compact ? " final-passage-context--compact" : ""}`}><div className="final-passage-sale-meta"><small>COMPLETED SALE CONTEXT</small><strong>ปิดการขาย {isoToThaiDisplay(sale.completedOn) || "-"}</strong><span>{show(sale.status)}</span></div><BirdIdentity bird={bird}/><CustomerContext customer={customer}/>{!compact && <p className="final-passage-payment">{linked.length ? `รายการชำระเงิน: ${linked.map(item => `${show(item.amount)} ${show(item.currency)}`).join(" · ")}` : "ยังไม่มีรายการชำระเงินที่ผูกกับ Sale นี้"}</p>}</section>;
}

function DeliveryTerms({ delivery, preview = false, currency }: { delivery: Row; preview?: boolean; currency?: string }) {
  const distance = Number(delivery.distanceKm), free = Number(delivery.freeDistanceKm), rate = Number(delivery.pricePerKm);
  const chargeable = Number.isFinite(distance) && Number.isFinite(free) ? Math.max(distance - free, 0) : null;
  const fee = preview ? (chargeable === null || !Number.isFinite(rate) ? null : chargeable * rate) : delivery.shippingFee;
  const unit = currency ?? String(delivery.currency ?? "");
  return <section className="delivery-terms" aria-label={preview ? "สรุปค่าจัดส่งที่คำนวณ" : "เงื่อนไขค่าจัดส่ง"}><small>{preview ? "AUTHORITATIVE PREVIEW" : "SHIPPING SNAPSHOT"}</small><div className="delivery-terms-equation"><span><b>{Number.isFinite(distance) ? distance : "—"}</b><em> กม.</em></span><i>−</i><span><b>{Number.isFinite(free) ? free : "—"}</b><em> กม. ฟรี</em></span><i>=</i><span><b>{chargeable ?? "—"}</b><em> กม. คิดค่าจัดส่ง</em></span><i>×</i><span><b>{Number.isFinite(rate) ? rate : "—"}</b><em> {unit || "—"}/กม.</em></span><i>=</i><strong>{fee === null || fee === undefined ? "—" : `${fee} ${show(unit)}`}</strong></div>{preview && <p>ค่าส่งเป็นผลคำนวณเพื่อส่งให้ trusted write; ไม่ใช่ช่องกรอก</p>}</section>;
}

function SaleSelector({ sales, birds, customers, payments, selected, onSelect, emptyText, title }: { sales: Row[]; birds: Row[]; customers: Row[]; payments: Row[]; selected: Row | null; onSelect: (sale: Row | null) => void; emptyText: string; title: string }) {
  const [query, setQuery] = useState(""); const normalized = query.trim().toLocaleLowerCase();
  const matches = useMemo(() => sales.filter(sale => { const bird = birds.find(item => item.birdId === sale.birdId), customer = customers.find(item => item.customerId === sale.customerId); return !normalized || [bird?.ringId, bird?.displayName, customer?.displayName, customer?.phone, customer?.email].some(value => String(value ?? "").toLocaleLowerCase().includes(normalized)); }).slice(0, 20), [sales, birds, customers, normalized]);
  if (selected) { const bird = birds.find(item => item.birdId === selected.birdId), customer = customers.find(item => item.customerId === selected.customerId); return <section className="final-passage-selected"><header><small>SELECTED HANDOFF CONTEXT</small><h3>{title}</h3></header><SaleContext sale={selected} bird={bird} customer={customer} payments={payments}/><button type="button" className="final-passage-quiet-action" onClick={() => onSelect(null)}>เปลี่ยนการขาย</button></section>; }
  return <section className="final-passage-selector"><header><small>COMPLETED SALE SELECTOR</small><h3>{title}</h3><p>เลือกบริบทการส่งต่อจาก Sale ที่ปิดแล้ว โดยไม่แสดงรหัสภายใน</p></header><label className="final-passage-search">ค้นหาการขายที่ปิดแล้ว<input aria-label="ค้นหาการขายที่ปิดแล้ว" placeholder="Ring ID ชื่อนก ชื่อลูกค้า โทรศัพท์ หรืออีเมล" value={query} onChange={event => setQuery(event.target.value)}/></label>{sales.length === 0 ? <p className="final-passage-empty">{emptyText}</p> : matches.length === 0 ? <p className="final-passage-empty">ไม่พบการขายที่ตรงกับการค้นหา</p> : <div className="final-passage-selector-list" role="listbox" aria-label="ผลการค้นหาการขายที่ปิดแล้ว">{matches.map(sale => { const bird = birds.find(item => item.birdId === sale.birdId), customer = customers.find(item => item.customerId === sale.customerId); return <button type="button" className="final-passage-selector-row" role="option" aria-selected="false" key={sale.saleId} onClick={() => { onSelect(sale); setQuery(""); }}><BirdIdentity bird={bird}/><CustomerContext customer={customer}/><span className="final-passage-selector-date">{isoToThaiDisplay(sale.completedOn) || "-"}<small>{show(sale.status)}</small></span></button>; })}</div>}</section>;
}

function DeliveryLedger({ deliveries, context }: { deliveries: Row[]; context: (saleId: unknown) => { bird?: Row; customer?: Row } }) {
  return <section className="delivery-ledger" aria-labelledby="delivery-ledger-title"><header><div><small>OPTIONAL DELIVERY LEDGER</small><h2 id="delivery-ledger-title">การจัดส่ง</h2><p>Delivery เป็นข้อมูล logistics ที่อาจมีได้หลายรายการ และไม่ใช่เงื่อนไขของการส่งมอบ</p></div><strong>{deliveries.length}<small>records</small></strong></header>{!deliveries.length ? <p className="final-passage-empty">ยังไม่มีประวัติการจัดส่ง — สามารถส่งมอบจาก Sale ที่ปิดแล้วได้โดยไม่ต้องมี Delivery</p> : <ol className="delivery-ledger-list">{deliveries.map((delivery, index) => { const { bird, customer } = context(delivery.saleId); return <li key={delivery.deliveryId}><span className="delivery-ledger-index">{String(index + 1).padStart(2, "0")}</span><div className="delivery-ledger-context"><BirdIdentity bird={bird}/><CustomerContext customer={customer}/></div><DeliveryTerms delivery={delivery}/><div className="delivery-ledger-status"><small>{isoToThaiDisplay(delivery.createdOn) || "-"}</small><TrustMarker>{show(delivery.status)}</TrustMarker><em>{show(delivery.distanceKm)} กม. · {show(delivery.shippingFee)} {show(delivery.currency)} · {show(delivery.status)}</em></div></li>; })}</ol>}</section>;
}

function HandoverLedger({ handovers, context }: { handovers: Row[]; context: (saleId: unknown) => { bird?: Row; customer?: Row } }) {
  return <section className="handover-ledger" aria-labelledby="handover-ledger-title"><header><div><small>HANDOFF MILESTONES</small><h2 id="handover-ledger-title">การส่งมอบ</h2><p>หลักฐานการส่งต่อที่แยกจาก Delivery record อย่างชัดเจน</p></div><strong>{handovers.length}<small>records</small></strong></header>{!handovers.length ? <p className="final-passage-empty">ยังไม่มีประวัติการส่งมอบ</p> : <ol className="handover-ledger-list">{handovers.map((handover, index) => { const { bird, customer } = context(handover.saleId), recipient = handover.recipientSnapshot as Row | undefined; return <li key={handover.handoverId}><span className="handover-ledger-index">{String(index + 1).padStart(2, "0")}</span><div className="handover-ledger-context"><BirdIdentity bird={bird} sold={handover.status === "completed"}/><CustomerContext customer={customer}/></div><RecipientSnapshot recipient={recipient}/><div className="handover-ledger-status"><ProvenanceMarker>{show(handover.status)}</ProvenanceMarker><strong>{isoToThaiDisplay(handover.handoverOn) || "-"}</strong><span>ผู้รับ: {show(recipient?.name)} · {isoToThaiDisplay(handover.handoverOn) || "-"} · {show(handover.status)}</span></div></li>; })}</ol>}</section>;
}

function DeliveryForm({ sale, birds, customers, payments, onSaved }: { sale: Row; birds: Row[]; customers: Row[]; payments: Row[]; onSaved: Refresh }) {
  const [distance, setDistance] = useState(""), [freeDistance, setFreeDistance] = useState(""), [price, setPrice] = useState(""), [currency, setCurrency] = useState("THB"), [date, setDate] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const numeric = [distance, freeDistance, price].map(Number), valid = [distance, freeDistance, price].every(value => value.trim() !== "") && numeric.every(value => Number.isFinite(value) && value >= 0), preview = valid ? { distanceKm: numeric[0], freeDistanceKm: numeric[1], pricePerKm: numeric[2] } : { distanceKm: Number.NaN, freeDistanceKm: Number.NaN, pricePerKm: Number.NaN };
  const bird = birds.find(item => item.birdId === sale.birdId), customer = customers.find(item => item.customerId === sale.customerId);
  const submit = async (event: FormEvent) => { event.preventDefault(); const createdOn = thaiDisplayToIso(date); if (!valid || !currency.trim() || !createdOn) { setMessage("กรุณากรอกข้อมูลการจัดส่งให้ถูกต้อง"); return; } setBusy(true); try { await invoke("createDelivery", { saleId: sale.saleId, distanceKm: numeric[0], freeDistanceKm: numeric[1], pricePerKm: numeric[2], currency: currency.trim(), createdOn }); setMessage("สร้างการจัดส่งสำเร็จ"); setDistance(""); setFreeDistance(""); setPrice(""); setCurrency("THB"); setDate(""); await onSaved(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <form className="final-passage-form final-passage-form--delivery" onSubmit={submit}><header><small>RECORD ACTIVITY</small><h3>เพิ่มการจัดส่ง</h3><p>บันทึก snapshot ค่าจัดส่งเฉพาะครั้งนี้</p></header><SaleContext sale={sale} bird={bird} customer={customer} payments={payments} compact/><div className="final-passage-form-grid"><label>ระยะทาง (กม.) *<input required type="number" step="any" aria-label="ระยะทาง (กม.)" value={distance} onChange={event => setDistance(event.target.value)}/></label><label>ระยะฟรี (กม.) *<input required type="number" step="any" aria-label="ระยะฟรี (กม.)" value={freeDistance} onChange={event => setFreeDistance(event.target.value)}/></label><label>ราคาต่อกม. *<input required type="number" step="any" aria-label="ราคาต่อกม." value={price} onChange={event => setPrice(event.target.value)}/></label><label>สกุลเงิน *<input required aria-label="สกุลเงินจัดส่ง" value={currency} onChange={event => setCurrency(event.target.value)}/></label><label>วันที่สร้างการจัดส่ง *<input required aria-label="วันที่สร้างการจัดส่ง" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event => changeDate(event.target.value, setDate)}/></label></div><DeliveryTerms delivery={preview} preview currency={currency}/><button disabled={busy}>{busy ? "กำลังบันทึก…" : "บันทึกการจัดส่ง"}</button>{message && <p role="status">{message}</p>}</form>;
}

function HandoverForm({ sale, birds, customers, payments, onSaved }: { sale: Row; birds: Row[]; customers: Row[]; payments: Row[]; onSaved: Refresh }) {
  const [name, setName] = useState(""), [phone, setPhone] = useState(""), [address, setAddress] = useState(""), [date, setDate] = useState(""), [review, setReview] = useState(false), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const bird = birds.find(item => item.birdId === sale.birdId), customer = customers.find(item => item.customerId === sale.customerId);
  const prepare = (event: FormEvent) => { event.preventDefault(); if (!name.trim() || !thaiDisplayToIso(date)) { setMessage("กรุณากรอกชื่อผู้รับและวันที่ส่งมอบให้ถูกต้อง"); return; } setMessage(""); setReview(true); };
  const confirm = async () => { const handoverOn = thaiDisplayToIso(date); if (!bird || !handoverOn) return; setBusy(true); try { await invoke("completeHandover", { sourceType: "sale", saleId: sale.saleId, birdId: bird.birdId, handoverOn, recipientSnapshot: { name: name.trim(), ...(phone.trim() ? { phone: phone.trim() } : {}), ...(address.trim() ? { address: address.trim() } : {}) } }); setMessage("ส่งมอบสำเร็จ"); setReview(false); setName(""); setPhone(""); setAddress(""); setDate(""); await onSaved(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <form className="final-passage-form final-passage-form--handover" onSubmit={prepare}><header><small>HANDOFF ACTIVITY</small><h3>ส่งมอบนก</h3><p>Delivery เป็นทางเลือก; การส่งมอบนี้คือ milestone ที่บันทึกผู้รับจริง</p></header><SaleContext sale={sale} bird={bird} customer={customer} payments={payments} compact/><div className="final-passage-form-grid"><label>ชื่อผู้รับ *<input required aria-label="ชื่อผู้รับ" value={name} onChange={event => setName(event.target.value)}/></label><label>เบอร์โทรศัพท์<input aria-label="เบอร์โทรศัพท์ผู้รับ" value={phone} onChange={event => setPhone(event.target.value)}/></label><label>ที่อยู่<input aria-label="ที่อยู่ผู้รับ" value={address} onChange={event => setAddress(event.target.value)}/></label><label>วันที่ส่งมอบ *<input required aria-label="วันที่ส่งมอบ" placeholder="DD/MM/YYYY" inputMode="numeric" value={date} onChange={event => changeDate(event.target.value, setDate)}/></label></div><button disabled={busy}>ตรวจสอบก่อนส่งมอบ</button>{message && <p role="status">{message}</p>}{review && <section className="handover-confirmation" role="dialog" aria-label="ยืนยันการส่งมอบ"><header><small>HANDOFF REVIEW</small><h4>ยืนยันการส่งมอบ</h4></header><BirdIdentity bird={bird}/><RecipientSnapshot recipient={{ name: name.trim(), ...(phone.trim() ? { phone: phone.trim() } : {}), ...(address.trim() ? { address: address.trim() } : {}) }}/><p>วันที่ส่งมอบ: {date}</p><div><button type="button" disabled={busy} onClick={confirm}>ยืนยันส่งมอบ</button><button type="button" className="final-passage-quiet-action" disabled={busy} onClick={() => setReview(false)}>ยกเลิก</button></div></section>}</form>;
}

export function DeliveryHandover({ eligibleSales, birds, customers, payments, deliveries, handovers, onRefresh }: { eligibleSales: Row[]; birds: Row[]; customers: Row[]; payments: Row[]; deliveries: Row[]; handovers: Row[]; onRefresh: Refresh }) {
  const [deliverySaleId, setDeliverySaleId] = useState<string | null>(null), [handoverSaleId, setHandoverSaleId] = useState<string | null>(null);
  const selectedDeliverySale = eligibleSales.find(sale => sale.saleId === deliverySaleId) ?? null, completedSaleIds = new Set(handovers.filter(item => item.status === "completed").map(item => item.saleId)), handoverSales = eligibleSales.filter(sale => !completedSaleIds.has(sale.saleId)), selectedHandoverSale = handoverSales.find(sale => sale.saleId === handoverSaleId) ?? null;
  const context = (saleId: unknown) => { const sale = eligibleSales.find(item => item.saleId === saleId); return { bird: birds.find(item => item.birdId === sale?.birdId), customer: customers.find(item => item.customerId === sale?.customerId) }; };
  return <section className="final-passage" aria-label="The Final Passage"><header className="final-passage-intro"><div><small>THE FINAL PASSAGE</small><h2>จากฟาร์ม ถึงมือลูกค้า</h2><p>บริบทการขายเป็นจุดอ้างอิง; Delivery คือบันทึก logistics แบบทางเลือก และ Handover คือหลักฐานการส่งต่อ</p></div><span>การส่งต่อที่ตรวจสอบย้อนกลับได้</span></header><DeliveryLedger deliveries={deliveries} context={context}/><SaleSelector title="เลือก Sale เพื่อบันทึก Delivery" sales={eligibleSales} birds={birds} customers={customers} payments={payments} selected={selectedDeliverySale} onSelect={sale => setDeliverySaleId(sale ? String(sale.saleId) : null)} emptyText="ไม่มีการขายที่ปิดแล้วสำหรับสร้างการจัดส่ง"/>{selectedDeliverySale && <DeliveryForm sale={selectedDeliverySale} birds={birds} customers={customers} payments={payments} onSaved={onRefresh}/>}<HandoverLedger handovers={handovers} context={context}/><SaleSelector title="เลือก Sale เพื่อส่งมอบ" sales={handoverSales} birds={birds} customers={customers} payments={payments} selected={selectedHandoverSale} onSelect={sale => setHandoverSaleId(sale ? String(sale.saleId) : null)} emptyText="ไม่มีการขายที่มีสิทธิ์ส่งมอบ"/>{selectedHandoverSale && <HandoverForm sale={selectedHandoverSale} birds={birds} customers={customers} payments={payments} onSaved={onRefresh}/>}</section>;
}
