import { FormEvent, useMemo, useState } from "react";
import { isoToThaiDisplay } from "./date";
import { DateInput } from "./DateInput";
import { invoke, thaiError } from "./functions";
import { OrangeRing } from "./bmb-design-system";
import { displayValue } from "./presentation";
import { EmptyState, PageHeader, SectionCard, StatusBadge } from "./ui";

type Row = Record<string, any>;

const birdLabel = (bird?: Row) => `${displayValue(bird?.displayName)} · Ring ID: ${displayValue(bird?.ringId)}`;

function GiveawayDetail({ data, onBack, onRefresh }: { data: Row; onBack: () => void; onRefresh: () => Promise<void> }) {
  const [handoverOn, setHandoverOn] = useState("");
  const [recipientName, setRecipientName] = useState("");
  const [phone, setPhone] = useState("");
  const [address, setAddress] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const action = async (operation: string) => { setBusy(true); setMessage(""); try { await invoke(operation, { giveawayId: data.giveawayId }); setMessage("บันทึกสถานะสำเร็จ"); await onRefresh(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  const handover = async (event: FormEvent) => { event.preventDefault(); if (!handoverOn || !recipientName.trim()) { setMessage("กรุณากรอกผู้รับจริงและวันที่ส่งมอบ"); return; } setBusy(true); setMessage(""); try { await invoke("completeHandover", { sourceType: "giveaway", giveawayId: data.giveawayId, birdId: data.birdId, handoverOn, recipientSnapshot: { name: recipientName.trim(), ...(phone.trim() ? { phone: phone.trim() } : {}), ...(address.trim() ? { address: address.trim() } : {}) } }); setMessage("ส่งมอบสำเร็จ"); await onRefresh(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  return <section><button type="button" onClick={onBack}>← กลับไปรายการให้</button><header className="detail-hero"><div><small>NON-SALE TRANSFER</small><h2>การให้โดยไม่ผ่านการขาย</h2><p>{birdLabel(data.bird)}</p></div><StatusBadge status={data.status}/></header><div className="detail-grid"><SectionCard title="บริบทนก"><p><OrangeRing variant="compact"/> {birdLabel(data.bird)}</p><p>วันที่บันทึกข้อตกลง: {isoToThaiDisplay(data.givenOn) || "-"}</p></SectionCard><SectionCard title="ความสัมพันธ์ลูกค้า"><p>{data.customer ? displayValue(data.customer.displayName) : "ไม่มี Customer reference"}</p><small>เป็นเพียงความสัมพันธ์ภายใน ไม่ใช่ผู้รับตามข้อเท็จจริง</small></SectionCard><SectionCard title="ผู้รับตามข้อตกลง"><p>{displayValue(data.recipientName)}</p><small>ไม่ถูกใช้แทน recipientSnapshot เมื่อส่งมอบจริง</small></SectionCard></div>{data.handover ? <SectionCard title="หลักฐานการส่งมอบ"><p>ผู้รับจริง: {displayValue(data.handover.recipientSnapshot?.name)}</p><p>วันที่ส่งมอบ: {isoToThaiDisplay(data.handover.handoverOn) || "-"}</p><StatusBadge status={data.handover.status}/></SectionCard> : <SectionCard title="สถานะการส่งมอบ"><p>ยังไม่มีหลักฐานการส่งมอบจริง</p></SectionCard>}{data.status === "planned" && <div className="quick-actions"><button disabled={busy} onClick={() => void action("completeGiveaway")}>ยืนยันข้อตกลงให้</button><button disabled={busy} onClick={() => void action("cancelGiveaway")}>ยกเลิก</button></div>}{data.status === "completed" && !data.handover && <form className="card form-zone" onSubmit={handover}><h3>ส่งมอบจริง</h3><p>ผู้รับจริงเป็น snapshot ใหม่ที่ไม่แทนที่ Customer หรือข้อมูลข้อตกลง</p><label className="field">ชื่อผู้รับจริง *<input aria-label="ชื่อผู้รับจริง" value={recipientName} onChange={event => setRecipientName(event.target.value)}/></label><label className="field">โทรศัพท์ผู้รับ<input aria-label="โทรศัพท์ผู้รับ giveaway" value={phone} onChange={event => setPhone(event.target.value)}/></label><label className="field">ที่อยู่ผู้รับ<input aria-label="ที่อยู่ผู้รับ giveaway" value={address} onChange={event => setAddress(event.target.value)}/></label><DateInput label="วันที่ส่งมอบ giveaway" required value={handoverOn} onChange={value => setHandoverOn(value ?? "")}/><button disabled={busy}>{busy ? "กำลังบันทึก…" : "ยืนยันการส่งมอบ"}</button></form>}{message && <p role="status">{message}</p>}</section>;
}

export function Giveaways({ giveaways, birds, customers, onRefresh }: { giveaways: Row[]; birds: Row[]; customers: Row[]; onRefresh: () => Promise<void> }) {
  const [selected, setSelected] = useState<Row | null>(null);
  const [birdId, setBirdId] = useState("");
  const [customerId, setCustomerId] = useState("");
  const [recipientName, setRecipientName] = useState("");
  const [givenOn, setGivenOn] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const availableBirds = useMemo(() => birds.filter(bird => !["sold", "given_away"].includes(String(bird.status))), [birds]);
  const open = async (giveaway: Row) => { setBusy(true); setMessage(""); try { setSelected(await invoke("getGiveawayDetails", { giveawayId: giveaway.giveawayId }) as Row); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  const create = async (event: FormEvent) => { event.preventDefault(); if (!birdId || !recipientName.trim() || !givenOn) { setMessage("กรุณากรอกนก ผู้รับตามข้อตกลง และวันที่ให้ครบ"); return; } setBusy(true); setMessage(""); try { await invoke("createGiveaway", { birdId, recipientName: recipientName.trim(), givenOn, ...(customerId ? { customerId } : {}) }); setBirdId(""); setCustomerId(""); setRecipientName(""); setGivenOn(""); setMessage("สร้างรายการให้สำเร็จ"); await onRefresh(); } catch (error) { setMessage(thaiError(error)); } finally { setBusy(false); } };
  if (selected) return <GiveawayDetail data={selected} onBack={() => setSelected(null)} onRefresh={async () => { await onRefresh(); setSelected(await invoke("getGiveawayDetails", { giveawayId: selected.giveawayId }) as Row); }}/>;
  return <><PageHeader eyebrow="NON-SALE TRANSFER" title="การให้" subtitle="ข้อตกลงให้และหลักฐานการส่งมอบจริงเป็นคนละขั้นตอน"/>{message && <p role="status">{message}</p>}<SectionCard title="รายการให้" subtitle="ไม่มี Sale, Payment หรือ Delivery ใน workflow นี้">{busy && <p className="muted">กำลังโหลดข้อมูล…</p>}{giveaways.length ? <div className="list">{giveaways.map((giveaway, index) => <button type="button" className="row" key={String(giveaway.giveawayId)} onClick={() => void open(giveaway)}><span>{String(index + 1).padStart(2, "0")}</span><span className="entity-primary"><small>GIVEAWAY</small><strong>{birdLabel(giveaway.bird ?? birds.find(bird => bird.birdId === giveaway.birdId))}</strong></span><span>{displayValue(giveaway.recipientName)}</span><span>{isoToThaiDisplay(giveaway.givenOn) || "-"}</span><StatusBadge status={giveaway.status}/></button>)}</div> : <EmptyState title="ยังไม่มีรายการให้"/>}</SectionCard><form className="card form-zone" onSubmit={create}><h2>สร้างรายการให้</h2><label className="field">นก *<select aria-label="นกสำหรับ Giveaway" value={birdId} onChange={event => setBirdId(event.target.value)}><option value="">เลือกนก</option>{availableBirds.map(bird => <option key={String(bird.birdId)} value={String(bird.birdId)}>{birdLabel(bird)}</option>)}</select></label><label className="field">Customer reference (ไม่บังคับ)<select aria-label="Customer สำหรับ Giveaway" value={customerId} onChange={event => setCustomerId(event.target.value)}><option value="">ไม่ผูก Customer</option>{customers.filter(customer => customer.status === "active").map(customer => <option key={String(customer.customerId)} value={String(customer.customerId)}>{displayValue(customer.displayName)}</option>)}</select></label><label className="field">ผู้รับตามข้อตกลง *<input aria-label="ผู้รับตามข้อตกลง" value={recipientName} onChange={event => setRecipientName(event.target.value)}/></label><DateInput label="วันที่บันทึกข้อตกลง" required value={givenOn} onChange={value => setGivenOn(value ?? "")}/><button disabled={busy}>{busy ? "กำลังบันทึก…" : "สร้างรายการให้"}</button></form></>;
}
