import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { DeliveryHandover } from "./DeliveryHandover";

const mocks=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock("./functions",()=>({invoke:mocks.invoke,thaiError:()=>"เกิดข้อผิดพลาด"}));
const birds=[{birdId:"bird-secret",ringId:"SMOKE-CHICK-01",displayName:"SMOKE Name CHICK 01",mutation:"Normal",currentSex:"male",status:"active"}];
const customers=[{customerId:"customer-secret",displayName:"SMOKE CUSTOMER 01",phone:"0812345678",email:"smoke.customer01@example.com"}];
const sales=[{saleId:"sale-secret",birdId:"bird-secret",customerId:"customer-secret",createdOn:"2026-08-14",completedOn:"2026-08-14",status:"completed"}];
const payments=[{paymentId:"payment-secret",saleId:"sale-secret",amount:5000,currency:"THB",status:"received"}];
const base={eligibleSales:sales,birds,customers,payments,deliveries:[],handovers:[],onRefresh:vi.fn()};
const selectSale=(index:number)=>fireEvent.click(screen.getAllByRole("option",{name:/SMOKE-CHICK-01/})[index]);

afterEach(()=>{cleanup();vi.clearAllMocks();});

it("searches eligible completed Sales and conceals every internal ID",()=>{render(<DeliveryHandover {...base}/>);fireEvent.change(screen.getAllByLabelText("ค้นหาการขายที่ปิดแล้ว")[0],{target:{value:"smoke.customer01"}});const matches=screen.getAllByRole("option",{name:/SMOKE CUSTOMER 01/});expect(matches.length).toBeGreaterThan(0);fireEvent.click(matches[0]);for(const id of ["sale-secret","bird-secret","customer-secret","payment-secret"])expect(document.body.textContent).not.toContain(id);expect(screen.getAllByText(/5000 THB/).length).toBeGreaterThan(0);});

it("calculates a live read-only fee preview for canonical zero and positive cases",()=>{render(<DeliveryHandover {...base}/>);selectSale(0);const form=screen.getByRole("heading",{name:"เพิ่มการจัดส่ง"}).closest("form")!,summary=within(form).getByLabelText("สรุปค่าจัดส่งที่คำนวณ");expect(within(form).queryByLabelText("ค่าส่ง")).toBeNull();expect(summary.textContent).toContain("—");const distance=within(form).getByLabelText("ระยะทาง (กม.)"),free=within(form).getByLabelText("ระยะฟรี (กม.)"),rate=within(form).getByLabelText("ราคาต่อกม.");for(const [d,f,r,charge,fee] of [["50","20","5","30 กม.","150 THB"],["50","30","3","20 กม.","60 THB"],["15","20","5","0 กม.","0 THB"],["20","20","5","0 กม.","0 THB"],["20","0","5","20 กม.","100 THB"],["20","0","0","20 กม.","0 THB"]]){fireEvent.change(distance,{target:{value:d}});fireEvent.change(free,{target:{value:f}});fireEvent.change(rate,{target:{value:r}});expect(summary.textContent).toContain(charge);expect(summary.textContent).toContain(fee);}});

it("creates Delivery without a client fee and displays authoritative persisted readback",async()=>{mocks.invoke.mockResolvedValue({deliveryId:"delivery-secret"});const onRefresh=vi.fn();const view=render(<DeliveryHandover {...base} onRefresh={onRefresh}/>);selectSale(0);const form=screen.getByRole("heading",{name:"เพิ่มการจัดส่ง"}).closest("form")!;for(const [label,value] of [["ระยะทาง (กม.)","20"],["ระยะฟรี (กม.)","5"],["ราคาต่อกม.","10"]])fireEvent.change(within(form).getByLabelText(label),{target:{value}});fireEvent.change(within(form).getByLabelText("วันที่สร้างการจัดส่ง"),{target:{value:"14082026"}});fireEvent.submit(form);expect(mocks.invoke).toHaveBeenCalledWith("createDelivery",{saleId:"sale-secret",distanceKm:20,freeDistanceKm:5,pricePerKm:10,currency:"THB",createdOn:"2026-08-14"});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(1));expect((within(form).getByLabelText("ระยะทาง (กม.)") as HTMLInputElement).value).toBe("");view.rerender(<DeliveryHandover {...base} deliveries={[{deliveryId:"delivery-secret",saleId:"sale-secret",distanceKm:20,freeDistanceKm:5,pricePerKm:10,shippingFee:150,currency:"THB",createdOn:"2026-08-14",status:"planned"}]}/>);expect(screen.getByText(/20 กม. · 150 THB · Planned/)).toBeTruthy();});

it("rejects negative Delivery values locally and preserves values on trusted failure",async()=>{mocks.invoke.mockRejectedValue(new Error("failed"));render(<DeliveryHandover {...base}/>);selectSale(0);const form=screen.getByRole("heading",{name:"เพิ่มการจัดส่ง"}).closest("form")!;const distance=within(form).getByLabelText("ระยะทาง (กม.)") as HTMLInputElement;fireEvent.change(distance,{target:{value:"-1"}});for(const [label,value] of [["ระยะฟรี (กม.)","0"],["ราคาต่อกม.","0"]])fireEvent.change(within(form).getByLabelText(label),{target:{value}});fireEvent.change(within(form).getByLabelText("วันที่สร้างการจัดส่ง"),{target:{value:"14082026"}});fireEvent.submit(form);expect(mocks.invoke).not.toHaveBeenCalled();expect(within(form).getByLabelText("สรุปค่าจัดส่งที่คำนวณ").textContent).toContain("—");fireEvent.change(distance,{target:{value:"0"}});fireEvent.submit(form);await waitFor(()=>expect(mocks.invoke).toHaveBeenCalledTimes(1));expect(distance.value).toBe("0");expect(screen.getByText("เกิดข้อผิดพลาด")).toBeTruthy();});

it("hands over the Sale Bird internally and refetches only after success",async()=>{mocks.invoke.mockResolvedValue({handoverId:"handover-secret"});const onRefresh=vi.fn();render(<DeliveryHandover {...base} onRefresh={onRefresh}/>);selectSale(1);const form=screen.getByRole("heading",{name:"ส่งมอบนก"}).closest("form")!;expect(within(form).queryByText(/Sale ID|Bird ID/)).toBeNull();fireEvent.change(within(form).getByLabelText("ชื่อผู้รับ"),{target:{value:"Receiver"}});fireEvent.change(within(form).getByLabelText("เบอร์โทรศัพท์ผู้รับ"),{target:{value:"099"}});fireEvent.change(within(form).getByLabelText("วันที่ส่งมอบ"),{target:{value:"15082026"}});fireEvent.submit(form);expect(screen.getByRole("dialog").textContent).not.toContain("sale-secret");fireEvent.click(screen.getByRole("button",{name:"ยืนยันส่งมอบ"}));expect(mocks.invoke).toHaveBeenCalledWith("completeHandover",{sourceType:"sale",saleId:"sale-secret",birdId:"bird-secret",handoverOn:"2026-08-15",recipientSnapshot:{name:"Receiver",phone:"099"}});await waitFor(()=>expect(onRefresh).toHaveBeenCalledTimes(1));});

it("excludes completed Handovers and preserves recipient input on failure",async()=>{const handovers=[{handoverId:"handover-secret",saleId:"sale-secret",birdId:"bird-secret",handoverOn:"2026-08-15",recipientSnapshot:{name:"Receiver"},status:"completed"}];const {rerender}=render(<DeliveryHandover {...base} handovers={handovers}/>);expect(screen.getByText("ไม่มีการขายที่มีสิทธิ์ส่งมอบ")).toBeTruthy();mocks.invoke.mockRejectedValue(new Error("failed"));rerender(<DeliveryHandover {...base}/>);selectSale(1);const form=screen.getByRole("heading",{name:"ส่งมอบนก"}).closest("form")!,name=within(form).getByLabelText("ชื่อผู้รับ") as HTMLInputElement;fireEvent.change(name,{target:{value:"Receiver"}});fireEvent.change(within(form).getByLabelText("วันที่ส่งมอบ"),{target:{value:"15082026"}});fireEvent.submit(form);fireEvent.click(screen.getByRole("button",{name:"ยืนยันส่งมอบ"}));await waitFor(()=>expect(screen.getByText("เกิดข้อผิดพลาด")).toBeTruthy());expect(name.value).toBe("Receiver");expect(document.body.textContent).not.toContain("Sold");});

it("presents optional multiple Delivery records and keeps Customer, Recipient, and authoritative Bird state distinct",()=>{const deliveries=[{deliveryId:"delivery-one",saleId:"sale-secret",distanceKm:20,freeDistanceKm:5,pricePerKm:10,shippingFee:150,currency:"THB",createdOn:"2026-08-14",status:"planned"},{deliveryId:"delivery-two",saleId:"sale-secret",distanceKm:8,freeDistanceKm:8,pricePerKm:10,shippingFee:0,currency:"THB",createdOn:"2026-08-15",status:"cancelled"}],handovers=[{handoverId:"handover-secret",saleId:"sale-secret",birdId:"bird-secret",handoverOn:"2026-08-16",recipientSnapshot:{name:"Recipient snapshot",phone:"099",address:"Trusted address"},status:"completed"}];const {container,rerender}=render(<DeliveryHandover {...base} deliveries={deliveries} handovers={handovers}/>);expect(screen.getByText(/Delivery เป็นข้อมูล logistics ที่อาจมีได้หลายรายการ/)).toBeTruthy();expect(screen.getByText("Recipient snapshot")).toBeTruthy();expect(screen.getAllByText("SMOKE CUSTOMER 01").length).toBeGreaterThan(0);expect(container.querySelectorAll(".orange-ring").length).toBeGreaterThan(0);expect(container.textContent).not.toContain("delivery-one");expect(container.textContent).not.toContain("handover-secret");expect(screen.queryByText("Sold")).toBeNull();rerender(<DeliveryHandover {...base} birds={[{...birds[0],status:"sold"}]} deliveries={deliveries} handovers={handovers}/>);expect(screen.getByText("Sold")).toBeTruthy();});
