const valueLabels: Record<string, string> = {
  active: "อยู่ในฟาร์ม",
  archived: "เก็บถาวร",
  cancelled: "ยกเลิก",
  closed: "ปิดรอบแล้ว",
  completed: "ขายเสร็จสิ้น",
  confirmed: "ยืนยันการขาย",
  deceased: "เสียชีวิต",
  delivered: "จัดส่งแล้ว",
  disabled: "ปิดการเผยแพร่",
  draft: "แบบร่าง",
  expired: "การจองหมดอายุ",
  external: "รับเข้าจากภายนอก",
  female: "ตัวเมีย",
  fertile: "มีเชื้อ",
  farm_hatched: "ฟักในฟาร์ม",
  full_refund: "คืนเงินเต็มจำนวน",
  hatched: "ฟักแล้ว",
  inactive: "พัก / แยกคู่",
  infertile: "ไม่มีเชื้อ",
  in_transit: "กำลังจัดส่ง",
  laid: "ออกไข่แล้ว",
  maintenance: "ปิดปรับปรุง",
  male: "ตัวผู้",
  no_refund: "ไม่คืนเงิน",
  other: "อื่น ๆ",
  partial_refund: "คืนเงินบางส่วน",
  planned: "วางแผนรอบเพาะ",
  published: "เผยแพร่แล้ว",
  sale: "การขาย",
  sold: "ขายแล้ว",
  superseded: "ถูกแทนที่",
  unknown: "ไม่ทราบเพศ",

  // Values below are intentionally left as their current English labels until
  // the owner explicitly approves Thai wording in the mapping workbook.
  deposit: "Deposit",
  discarded: "Discarded",
  dna: "DNA",
  final: "Final",
  given_away: "Given Away",
  list: "List",
  lost: "Lost",
  offer: "Offer",
  purchased: "Purchased",
  received: "Received",
  rescued: "Rescued",
  reserved: "Reserved",
  retired: "Retired",
  sale_payment: "Sale Payment",
  sex_linked: "Sex Linked",
  visual: "Visual",
  voided: "Voided",
};

const fieldLabels: Record<string, string> = {
  activeOn: "Active On",
  birdId: "Bird ID",
  breedingCycleId: "Breeding Cycle ID",
  cageId: "Cage ID",
  customerId: "Customer ID",
  cycleId: "Cycle ID",
  deliveryId: "Delivery ID",
  displayName: "Display Name",
  eggId: "Egg ID",
  handoverId: "Handover ID",
  hatchedOn: "Hatched On",
  laidOn: "Laid On",
  pairId: "Pair ID",
  passportStatus: "Passport Status",
  paymentId: "Payment ID",
  publicToken: "Public Token",
  reservationId: "Reservation ID",
  ringId: "รหัสห่วงขา",
  saleId: "Sale ID",
  sequenceNo: "Sequence No.",
  startedOn: "Started On",
  status: "สถานะ",
};

export const displayValue = (value: unknown) => valueLabels[String(value)] ?? String(value ?? "-");
export const displayFieldName = (value: string) => fieldLabels[value] ?? value.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/^./, letter => letter.toUpperCase());
